### ISSUE TITLE
How to match the custom tag in html or vue ?

### ISSUE THREAD

**Issue by Jax0rz** [facelessuser/BracketHighlighter#594] opened 2021-09-05 08:14 UTC
<img width="1904" alt="CleanShot 2021-09-05 at 16 10 35@2x" src="https://user-images.githubusercontent.com/7557357/132120229-e5828e87-2143-4f2b-87f9-9c0a8dd5eed3.png">

**Comment by facelessuser** [comment] 2021-09-06 02:27
@Jax0rz As long as the tag is recognized with basic HTML syntax and `HelloWorld` looks like it does, BH can find it. The problem is that it will expect a closing tag.

<img width="324" alt="Screen Shot 2021-09-05 at 8 10 27 PM" src="https://user-images.githubusercontent.com/1055125/132150782-a9b64bb2-027c-48c0-90c3-ecff2acf7889.png">

The rules are a bit different for XML though:

<img width="330" alt="Screen Shot 2021-09-05 at 8 11 09 PM" src="https://user-images.githubusercontent.com/1055125/132150834-52557cc5-bfef-4fbe-bb64-9e25e05fb5e4.png">

So you need to tell BracketHighlighter that `HelloWorld` is a "void" element as it looks like that is what you want in this case:

> A void element is an element whose content model never allows it to have contents under any circumstances. Void elements can have attributes.

So, go to `Preferences->Package Settings->BracketHighlighter->Tag Settings` and copy the void settings to your User `bh_tag.sublime-settings` file. Add `helloworld` and you should be good to go.

```js
{
    // Tags that never have a closing.  You can use 'null' if it does not require a pattern.
    "void_tag_patterns": {
        "xml": null,
        "xhtml": null,
        "html": "helloworld|area|base|basefont|br|col|embed|frame|hr|img|input|isindex|keygen|link|meta|param|source|track|wbr",
        "cfml": "area|base|basefont|br|col|embed|frame|hr|img|input|isindex|keygen|link|meta|param|source|track|wbr"
    },
}
```

We can now see with HTML syntax set that we can highlight the void tag just fine.

<img width="719" alt="Screen Shot 2021-09-05 at 8 18 20 PM" src="https://user-images.githubusercontent.com/1055125/132151741-9d35d73c-6b7c-4254-9901-5c9f2e667d13.png">

If you need to recognize both `<el></el>` and `<el />` form, then maybe use `self_closing_tag_patterns`. This treats the element much like an XML/XHTML element.

Documentation  reference:

- https://facelessuser.github.io/BracketHighlighter/customize/#void_tag_patterns
- https://facelessuser.github.io/BracketHighlighter/customize/#self_closing_tag_patterns

@gir-bot remove S: triage
@gir-bot  add T: support

**Closed** 2021-09-08 03:45 UTC
Labels: T: support
