### ISSUE TITLE
Swap bug

### ISSUE THREAD

**Issue by AmjadHD** [facelessuser/BracketHighlighter#569] opened 2020-10-11 21:49 UTC
## Description

Swap doesn't work:
![bh_swap_bug1](https://user-images.githubusercontent.com/33235928/95691122-0c9af980-0c1d-11eb-9901-0148055faffe.gif)

## Support Info

- ST ver.: 3211
- Platform: windows
- Arch: x64
- Plugin ver.: 2.28.1
- Install via PC: True
- mdpopups ver.: 3.7.5
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

See the screen-cast.

**Comment by facelessuser** [comment] 2020-10-11 21:52
Can you post some copy/pastable code so I can recreate? Also, what sublime syntax are you using?

@gir-bot add S: more-info-needed

**Comment by AmjadHD** [comment] 2020-10-11 21:56
>Can you post some copy/pastable code so I can recreate?

this happens with any code.
>Also, what sublime syntax are you using?

The builtin python syntax

**Comment by facelessuser** [comment] 2020-10-11 22:00
Not from what I see.

**Comment by facelessuser** [comment] 2020-10-11 22:03
![bh_swap](https://user-images.githubusercontent.com/1055125/95691282-3e8b6c00-0bdb-11eb-8d86-d1cd473f52d0.gif)

You can see here.  This is why I ask for copy/pastable examples with details.

**Comment by facelessuser** [comment] 2020-10-11 22:04
You can't see well in the gif, but I am using "outside adjacent" and the cursor is to the left of the first bracket. Using default Python. 🤷

**Comment by AmjadHD** [comment] 2020-10-11 22:14
Well, It happens regardless of the syntax or the position of the caret, whether adjacent to a bracket or not.

**Comment by facelessuser** [comment] 2020-10-11 22:18
Maybe it is a 3211 thing. At least on ST4, I do not see this issue at all. I suspect you have another plugin interfering, and this has nothing to do with BH. I will try this out on a portable ST3 in a bit, but if I cannot reproduce, I'll have to close the issue and assume you have a local issue unless some further info can be provided.

**Comment by AmjadHD** [comment] 2020-10-11 22:32
I disabled all plugins and still it does it.

**Comment by AmjadHD** [comment] 2020-10-11 22:33
I remember that it used to work.

**Comment by facelessuser** [comment] 2020-10-11 22:48
I did it in a fresh ST3 portable install, absolutely no issue. Maybe I'm somehow approach something wrong, but based on the info you've provided, I do see happening what your image is showing.

**Comment by facelessuser** [comment] 2020-10-11 22:53
I'm going to flat this with a `wontfix` for now. Unless I can get some steps to reproduce, it looks to me like whatever you are experiencing is specific with your local computer.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by facelessuser** [comment] 2020-11-18 14:31
I've simply not been able to reproduce this. If I stumble upon this in the future, I'll be happy to fix it, but until I can actually reproduce, there is nothing I can do.

**Closed by facelessuser** 2020-11-18 14:31 UTC
Labels: S: more-info-needed, S: wontfix
