### ISSUE TITLE
Automatic bracket matching seems to fail in 2nd file window when using New View Into File

### ISSUE THREAD

**Issue by mgleavitt** [facelessuser/BracketHighlighter#413] opened 2017-04-25 19:04 UTC
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request.

---

## Description

After I installed package (including turning of default matching per quick start) & closed/opened ST3, I wasn't seeing expected interactive default bracket matching behavior. Experimentation showed that it's working fine in my environment, *except in windows displaying 2nd view into a file (via New View Into File)* 

When viewing the same file in, say, a 2 row layout w/original on top & "new view" on bottom, the top works as expected, but the bottom view only works in response to command palette (e.g., jump to right bracket).

Behavior doesn't seem to be layout specific; I get same thing if I'm in a single-pane display with the two views on different tabs.

User settings:
{
	"color_scheme": "Packages/Color Scheme - Default/Sunburst.tmTheme",
	"font_size": 11,
	"ignored_packages":
	[
		"Vintage"
	],
	"match_brackets": false,
	"match_brackets_angle": false,
	"match_brackets_content": false,
	"match_brackets_square": false,
	"match_tags": false,
	"tab_size": 2
}

No obvious console output.

## Support Info

Support info:
- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.23.3
- Install via PC: True
- mdpopups ver.: 1.13.1
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Open file (in my case a JavaScript file) in ST3
2. Verify default automatic bracket matching behavior
3. File > New View into File
4. Go to tab displaying second view
5. Automatic/interactive bracket matching doesn't work (for me), but command palette actions do

**Comment by facelessuser** [comment] 2017-04-25 19:14
As I recall, those "cloned" views don't have event listeners attached to them.  I don't think there is anything I can do about it as it is a limitation of Sublime Text.

**Comment by facelessuser** [comment] 2017-04-25 19:19
This is a duplicate of #356.  I knew this sounded familiar :slightly_smiling_face:.  I believe my answer will remain the same as what I said there.  As this is a duplicate, I will close this issue.

**Closed by facelessuser** 2017-04-25 19:19 UTC
