### ISSUE TITLE
Implement what BracketGuard does (Sorry this is not an issue, didn't know how to contact you)

### ISSUE THREAD

**Issue by eorroe** [facelessuser/BracketHighlighter#229] opened 2015-02-25 14:02 UTC
Thank you for the package love it.

Can you please implement what BracketGuard does: https://packagecontrol.io/packages/BracketGuard

I prefer to have your package with BrackeGuard's feature than to have both.

I'm not sure about copyrights, but if possible please do. 

Thank You

**Comment by facelessuser** [comment] 2015-02-25 14:23
BH, in a number of cases, will show you it can't match a bracket.  Admittedly, it won't always as the algorithm was designed for matching, not identifying mismatched brackets.

I could maybe improve the algorithm to possibly pair am unmatched bracket with where it expected to find the other bracket, showing invalid opening and closing and maybe improve invalid catching, but everything is streamlined for focusing on the current bracket scope.  I doubt I would change the algorithm to scan globally all brackets.

**Comment by eorroe** [comment] 2015-02-25 14:36
What if you only scan mismatched in the scopes. Because programmers are likely to mismatch a bracket only where there current scope is.

**Comment by facelessuser** [comment] 2015-02-25 14:39
I guess I would need to better understand what you mean, can you explain how you invision it would work?  Then I can contrast that with the current framework.

**Comment by eorroe** [comment] 2015-02-25 14:46
Ok using BracketHighlighter the brackets are only highlighted depending on where my cursor is. So instead of searching the whole file for bracketMismatch, only search the scope of where my cursor is for bracketMismatch?

Yet seeing how BracketGuard works you'll probably have to go up the parent scope to find the mismatch, because I believe when there's a mismatch no scope is found.

**Comment by facelessuser** [comment] 2015-02-25 16:23
The way BH works, is it either takes the entire view buffer in the case of on demand matches via shortcuts or command palette, or  a limited window on automatic matches for performance.

Using the enabled rules, it complies two lists of brackets; opening and closing.  It then starts paring up brackets until it is left with the closest opening that cannot be matched on the left side of the cursor.  Then it searches the right side resolving brackets until it finds the one that matches the opening.

But BH is designed to kick out as soon as it finds what it needs though.  So yes, it takes parents into consideration, but only as much as it needs to.

The algorithm always defaults search starting from the left, that is why it won't always show the invalid question mark if the opening bracket is missing on the left side opposed to the right; it doesn't even bother searching the right side for closing brackets if a valid opening is not found.  This was done for performance.  The opening searches inwards from the outside of the region to make sure the opening bracket makes sense and doesn't get paired incorrectly with a like type.  And the closing bracket search searches outwards from the cursor comparing against the opening.  So it is coded to  A matter of fact, the closing bracket search algorithm I believe is coded to compare against the found opening.  So it is coded strongly to find a bracket match and kick out as soon as it knows it is fruitless to continue further.

So to get what you want, would require a rework of the algorithm and a possible performance hit.  Mainly I would have to implement a right side search that also searches out to in and run it regardless of whether a bracket on the left was found.  I would also need to change how I flag a bracket as invalid as currently if I can find only one, it is invalid, but in your desired case, you could have an invalid and have to bad brackets to highlight.  So there would need to be substantial changes to the algorithm and how it interacts with bh_plugins.

**Comment by eorroe** [comment] 2015-02-25 16:51
Ok. I don't understand how sublime plugins work. But just a thought:

can't you like say copy bracketGuard's function and have your package run both?

Instead of having to mess with your original code?

**Comment by facelessuser** [comment] 2015-02-25 17:06
I'm not saying I won't implement something better for catching bad brackets, I am just laying out the pros/cons and giving an explanation as to why it wouldn't be a simple quick add.

> But just a thought:
can't you like say copy bracketGuard's function and have your package run both?
Instead of having to mess with your original code?

I guess my counterargument would be: couldn't you just install both plugins?

Keep in mind, bracketguard is approaching this with a very specific goal it wants to accomplish. BH is approaching this with a completely different mindset and goals.

BracketGaurd is very simplistic in its implementation.  It won't catch complex brackets like ruby's `if` `end` blocks.  I had to completely redesign BH to handle custom blocks such as Ruby's as before BH only handled `[] () {}` and hardcoded algorithm for tags.  Everything has been generalized in BH so that almost any open and closing block marker can be targeted.  With that comes complexity.  So copy and paste is a no go, but you can run both plugins side by side (I guess their highlighting may interfere).  Given some time, and if I decide to move forward on this, I could greatly improve BH's invalid bracket matching.

Keep in mind that BH not matching brackets also tells you a lot about invalid brackets.  If a bracket won't highlight, you can quickly select brackets on the other side and quickly understand where the problem is.  Yeah it doesn't currently auto-highlight your problem, but you can quickly detect the exact problem by using what it does tell you.

**Comment by eorroe** [comment] 2015-02-25 17:11
Oh Ok thanks Please let me know through here or whenever you update pop it up on my sublime text. Thanks. 

Oh and just found this package (just incase you haven't seen it): https://packagecontrol.io/packages/EasyMotion

Really cool.

**Comment by facelessuser** [comment] 2015-04-16 20:59
After thinking about this more, I really don't have any intention to add this at this time.  If I change my mind in the future, then I will, but I will consider this request as a `will_not_fix` and close the issue.

**Closed by facelessuser** 2015-04-16 20:59 UTC
Labels: Enhancement, Won't Fix

**Comment by eorroe** [comment] 2015-04-16 22:52
Ok thanks.
