### ISSUE TITLE
Bracket not matching up properly

### ISSUE THREAD

**Issue by saurabh-gohil** [facelessuser/BracketHighlighter#453] opened 2017-11-15 10:03 UTC
BH is not matching bracket even if ignore threshold is set to true.
Check the 1st image.
![1](https://user-images.githubusercontent.com/7500357/32829999-d87b566a-ca19-11e7-93b6-536f058b2def.png)

However, when I select the closing bracket manually BH shows the correct opening bracket.
![2](https://user-images.githubusercontent.com/7500357/32830037-f3be991e-ca19-11e7-8b08-05a3379dfa42.png)

But it fails to match from an opening bracket.
I am using Sublime Text 3 build 3154 with the default setting for BH.

Kindly help to solve the issue.

Support Info:
- ST ver.: 3154
- Platform: linux
- Arch: x64
- Plugin ver.: 2.26.0
- Install via PC: True
- mdpopups ver.: 3.1.3
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment] 2017-11-15 13:37
My first assumption would be that the is something wrong with your code, but there is not enough context in your screenshot to determine what the issue would be.

Please post, in plain text, a minium amount of code needed to reproduce your error, and post the syntax language you are using. If the syntax language is not a default syntax language, provide a link to where I can get that syntax.

Obviously I don't want to see proprietary code, so you may have to code up a simple failing example.

**Comment by saurabh-gohil** [comment] 2017-11-15 14:04
Language is PHP, I will share the dummy code to reproduce the error soon.
But I have noticed this issue when you have a lengthy code.

**Comment by mfl5** [comment] 2017-12-01 18:50
I'm having the same issue and there is no problem with my code (code is already compiled / deployed and working properly). Some brackets seem to work (typically easy ones that don't have too many nested brackets under them) whereas other brackets don't and show the '?' (typically ones that do have a lot of other nested brackets under them). I haven't done a lot of testing with this to identify the cause of the bug other than too many brackets being nested possibly, but it definitely appears to be a bug.

**Comment by facelessuser** [comment] 2017-12-01 18:54
Without an example that I can copy and paste to reproduce, this isn't going to get looked at.  Please post a failing example I can copy and paste.

**Comment by mfl5** [comment] 2017-12-01 19:01
I figured it out, I needed the ignore_threshold option. Odd that this isn't
enabled by default though, it's so easy to go beyond.

Thanks!


--
Mark Levy
Database Administrator, Enterprise Learning

P: 646-997-3630

F: 718-260-3571



<http://engineering.nyu.edu/>


NYU Tandon Online <http://engineering.nyu.edu/academics/online> | Executive
Programs
<http://engineering.nyu.edu/enterprise-learning/programs/executive-programs>

________________________________________

Connect with us:
<https://www.linkedin.com/company/nyu-epoly-online-graduate-program?trk=biz-brand-tree-co-logo>
<https://www.facebook.com/NYUTandonOnline/>
<https://twitter.com/nyutandononline>  [image:
Badge-OnlinePrograms-GradEngineering-2017.png]
<http://www.usnews.com/education/online-education/engineering/rankings?int=a38e09>[image:
Badge-OnlinePrograms-GradCIT-2017.png]
<http://www.usnews.com/education/online-education/computer-information-technology/rankings?int=9e1708>

**Comment by saurabh-gohil** [comment] 2017-12-02 06:58
As you requested dummy code to reproduce the issue, Please check following PHP snippet.
I am getting the same issue when file contains only following of code.
Hope it helps to find out the issue
Let me know in case any more details ae required.
```
function getFiles($directory, $extension = null, $age = null, $search = null, $fileType = "older", $howMuch = 600)
{
    $filesArray = array();
    $files      = new DirectoryIterator($directory);
    foreach ($files as $file)
    {
        if (!$file->isDot() && $file->isFile())
        {
            if ($age != "")
            {
                if ($fileType == "older")
                {
                    if ($file->getMTime() >= strtotime($age))
                    {
                        continue;
                    }
                }
                else if ($fileType == "newer")
                {
                    if ((time() - $file->getMTime()) >= $age)
                    {
                        continue;
                    }
                }
            }
            if ($search != "" && !stristr($file->getFilename(), $search))
            {
                continue;
            }

            if ($extension == "")
            {
                $filesArray[$file->getFilename()] = $file->getPath() . DIRECTORY_SEPARATOR . $file->getFilename();
            }
            else if (($file->getExtension() == $extension))
            {
                $filesArray[$file->getFilename()] = $file->getPath() . DIRECTORY_SEPARATOR . $file->getFilename();
            }
        } // if ends
    } // foreach ends
    if (count($filesArray) > 0)
    {
        print_r(count($filesArray));
        return $filesArray;
    }
    return false;
}
```

**Comment by facelessuser** [comment] 2017-12-03 03:16
1. I am assuming you are using the default PHP syntax, if not, please tell me what you are using with a link to the 3rd party syntax.

2. > BH is not matching bracket even if ignore threshold is set to true.

    Please don't do that. It is just going to give you performance issues in large files.

3. The example you gave me will not match things proper as there needs to be a `<?php` or `<?` at the start of the file for it to get highlighted as PHP.  Then things will be highlighted proper and BH will be able to avoid `->` as scopes that BH can ignore will be assigned to those characters, but until then, BH will keep tripping on those characters.

    ```php
    <?php
    function getFiles($directory, $extension = null, $age = null, $search = null, $fileType = "older", $howMuch = 600)
    {
        $filesArray = array();
        $files      = new DirectoryIterator($directory);
        foreach ($files as $file)
        {
            if (!$file->isDot() && $file->isFile())
            {
                if ($age != "")
                {
                    if ($fileType == "older")
                    {
                        if ($file->getMTime() >= strtotime($age))
                        {
                            continue;
                        }
                    }
                    else if ($fileType == "newer")
                    {
                        if ((time() - $file->getMTime()) >= $age)
                        {
                            continue;
                        }
                    }
                }
                if ($search != "" && !stristr($file->getFilename(), $search))
                {
                    continue;
                }

                if ($extension == "")
                {
                    $filesArray[$file->getFilename()] = $file->getPath() . DIRECTORY_SEPARATOR . $file->getFilename();
                }
                else if (($file->getExtension() == $extension))
                {
                    $filesArray[$file->getFilename()] = $file->getPath() . DIRECTORY_SEPARATOR . $file->getFilename();
                }
            } // if ends
        } // foreach ends
        if (count($filesArray) > 0)
        {
            print_r(count($filesArray));
            return $filesArray;
        }
        return false;
    }
    ```

So, things are working for me as long as I have `<?php` or `<?` at the file's start:

![screenshot 2017-12-02 20 01 53](https://user-images.githubusercontent.com/1055125/33521868-cd43380a-d79b-11e7-8c87-c967f1dad32d.png)

Now if this is in an HTML file that is not highlighting PHP content as PHP, then it is because `->` doesn't have a scope applied to it, and neither will less than or greater than symbols. If BH doesn't know it those symbols are in PHP syntax, it can't resolve them as it triggers on `<` and `>` when looking for tags.

**Comment by facelessuser** [comment] 2017-12-03 03:44
It's possible instead of excluding certain scopes, we can flip it and only include certain scopes...At least then we could avoid `<` and `>` in all cases except when it is scoped like it is in an HTML tag.  I'd have to look at HTML scoping before doing those to make sure this would be a legitimate approach.

**Comment by saurabh-gohil** [comment] 2017-12-03 07:05
I am using default PHP syntax only and I have opening PHP statement `<?php` at the beginning.
However, I tried the same patch of code on my windows machine which works fine but same code is not working on my laptop with Ubuntu.
Do you think other plugins might be conflicting with BH?
If that is the case then how can we debug it?

**Comment by saurabh-gohil** [comment] 2017-12-03 07:07
I am using default PHP syntax only and I have opening PHP statement <?php at the beginning.
However, I tried the same patch of code on my windows machine which works fine but the same code is not working on my laptop with Ubuntu.
Do you think other plugins might be conflicting with BH?
If that is the case then how can we debug it?

**Comment by facelessuser** [comment] 2017-12-03 07:16
> Do you think other plugins might be conflicting with BH?

Could be.  In reality, the main plugin that would affect BH in this way is if you were using a different syntax than the default.  Like some 3rd party PHP or something like that.  I'd be interested to see if you've installed any 3rd party PHP or HTML syntaxes.

Can you post a list of installed plugins that are on the failing machine?

---

On a side note, I probably will be changing how we target angles in the future. Whitelisting a tags opening and closing angles in a tag seems to work much better than blacklisting problem angles as people discover them.

**Comment by saurabh-gohil** [comment] 2017-12-03 07:27
> Can you post a list of installed plugins that are on the failing machine?

Yes, I will post the list of installed plugins as soon as I start the laptop.

**Comment by saurabh-gohil** [comment] 2017-12-03 10:07
Here is the list of packages currently installed.

> A File Icon
> Alignment
> Bootstrap 3 Autocomplete
> BracketHighlighter
> CodeFormatter
> Color Highlighter
> DocBlockr
> FileHeader
> Function Name Display
> GitGutter
> INI
> Insert Nums
> jQuery
> Local History
> Package Control
> Paste as Column
> Sassy Comments
> SFTP
> SideBarEnhancements
> SublimeCodeIntel
> SublimeLinter
> SublimeLinter-csslint
> SublimeLinter-json
> SublimeLinter-pep8
> SublimeLinter-php
> SublimeLinter-pyflakes
> SublimeLinter-shellcheck
> SyncedSideBar
> Toggle Word

**Comment by facelessuser** [comment] 2017-12-03 15:21
Unfortunately, none of those stand out to me as problematic.  I don't know if you've ever manually checked out BracketHIghlighter or used something like Package Resources to unpack BracketHighlighter before, but I'd check the location of your installed packages `Sublime Text 3->Packages` and `Sublime Text 3->Installed Packages`.  Package control should have installed in the `Installed Packages` location.  You should **not** have one in the normal `Packages` location.  If you do, some of those files can override the `Installed Packages` one causing unexpected issues.

If that is not the case, I'd next want to see your user `User/bh_core.sublime-settings` file to see if you have any rule overrides.

**Comment by saurabh-gohil** [comment] 2017-12-04 05:28
BH is installed in `Installed Packages` so there no override.
As you pointed out that issue might be with the user config and you are correct.
I removed user config and let BH run on the default setting and viola it is working as expected.
But would like to know which settings in user config are conflicting.
Please take a look at my user config given below.
```
{
    // Debug logging
    "debug_enable": false,

    // Try to ensure dependencies are up to date.
    // If it is not desirable to have this done (like developing) on a specific dependency,
    // or some other reason, set this to False.
    "upgrade_dependencies": true,

    // When only either the left or right bracket can be found
    // this defines if the unmatched bracket should be shown.
    "show_unmatched": true,

    // Do the opposite of "show_unmatched" for the languages listed below
    "show_unmatched_exceptions": [],

    // Enable high visibility by default when sublime starts up
    // If sublime is already running and this gets changed,
    // you will not see any changes (restart required to see change)
    "high_visibility_enabled_by_default": false,

    // Experimental: Creates a visible bar at the beginning of all lines between
    // multiline bracket spans.
    "content_highlight_bar": true,

    // Show hover popup
    // This will show a hover popup when mousing over
    // the visible bracket if the other
    // highlighted matching bracket is off screen.
    // It will show line text of the off screen bracket -/+ 128 chars
    // from the bracket start and end points.
    // A link will be available allowing the user to click and jump to
    // the other bracket.
    "show_offscreen_bracket_popup": true,

    // Adjust char per line context of bracket popup.
    "popup_char_context": 120,

    // Adjust number of lines of additional context
    // that are shown when brackets are vertically off screen.
    // Specified line count is split to context before and after the target line.
    // So a value of 4 would give you two lines of context before and two lines after.
    "popup_line_context": 4,


    // Experimental: Use 'popup_bracket_emphasis' to customize the popup's bracket emphasis color
    "use_custom_popup_bracket_emphasis": false,

    // Experimental: Specify the scope (to get color) to emphasize the off screen bracket
    // in popups.  Alternatively you can use a hex value in the form '#rgb' or '#rrggbb'.
    "popup_bracket_emphasis": "keyword",

    // Experimental: Align the content highlight bar at the bracket indent level
    "align_content_highlight_bar": true,

    // Experimental: Allow bracket highlighter to search in widgets.
    // Most widgets use Plain Text which BH should ignore,
    // But regex find views views are usually regular expression
    // Which should be the only views to trigger BH.
    "search_in_widgets": true,

    // Show brackets in the minimap.
    // Depending on your highlight style, regions may not be visible in minimap.
    // "underline" won't show up due to it being a style consisting of
    // multiple zero width selections to create a fat underline.
    // But the following styles should show up fine as they are normal regions styles:
    //     - thin_underline
    //     - solid
    //     - outline
    //     - squiggly
    //     - stippled
    "show_in_minimap": false,

    // High visibility style and color for high visibility mode
    // (solid|outline|underline)
    // ST3 has additional options of (thin_underline|squiggly|stippled)
    "high_visibility_style": "outline",

    // (scope|__default__|__bracket__)
    "high_visibility_color": "__bracket__",

    // Match brackets only when the cursor is touching the inside of the bracket
    "match_only_adjacent": false,

    // Outside adjacent bracket matching
    "bracket_outside_adjacent": true,

    // Experimental: Special matching mode for block cursor.
    // Essentially, this provides a matching mode that makes a little more
    // sense to some in regards to the visual representation of block cursors.
    // This will ignore "bracket_outside_adjacent".
    "block_cursor_mode": true,

    // When "bracket_outside_adjacet" is set, and a plugin command explicitly sets
    // "no_outside_adj" to "None" instead of "true" or the default "false",
    // this value will be used.
    "ignore_outside_adjacent_in_plugin": true,

    // When "block_cursor_mode" is set, and a plugin command explicitly sets
    // "no_block_mode" to "None" instead of "true" or the default "false",
    // this value will be used.
    "ignore_block_mode_in_plugin": true,

    // Character threshold to search
    "search_threshold": 5000,

    // Ignore threshold
    "ignore_threshold": true,

    // Set mode for string escapes to ignore (regex|string)
    "bracket_string_escape_mode": "string",

    // Set max number of multi-select brackets that will be searched automatically
    "auto_selection_threshold" : 10,

    // Enable this to completely kill highlighting if "auto_selection_threshold"
    // is exceeded.  Default is to highlight up to the "auto_selection_threshold".
    "kill_highlight_on_threshold": true,

    // Disable gutter icons when doing multi-select
    "no_multi_select_icons": false,

    // Rules that define the finding and matching of brackets
    // that are contained in a common scope.
    // Useful for bracket pairs that are the same but
    // share a common scope.  Brackets are found by
    // Finding the extent of the scope and using regex
    // to look at the beginning and end to identify bracket.
    // Use only if they cannot be targeted with traditional bracket
    // rules.
    "scope_brackets": [
        // Quotes
        {
            "name": "py_single_quote",
            "open": "(?:u|b|f)?r?((?:'')?')",
            "close": "((?:'')?')",
            "style": "single_quote",
            "scopes": ["string", "meta.string"],
            "language_filter": "whitelist",
            "language_list": [
                "Python",
                "PythonImproved",
                "MagicPython"
            ],
            "sub_bracket_search": "true",
            "plugin_library": "bh_modules.pyquotes",
            "enabled": true
        },
        {
            "name": "py_double_quote",
            "open": "(?:u|b|f)?r?((?:\"\")?\")",
            "close": "((?:\"\")?\")",
            "style": "double_quote",
            "scopes": ["string", "meta.string"],
            "language_filter": "whitelist",
            "language_list": [
                "Python",
                "PythonImproved",
                "MagicPython"
            ],
            "sub_bracket_search": "true",
            "plugin_library": "bh_modules.pyquotes",
            "enabled": true
        },
        {
            "name": "single_quote",
            "open": "(')",
            "close": "(')",
            "style": "single_quote",
            "scopes": ["string", "string.quoted"],
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        {
            "name": "double_quote",
            "open": "(\")",
            "close": "(\")",
            "style": "double_quote",
            "scopes": ["string", "string.quoted"],
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        {
            "name": "backtick_quote",
            "open": "(`)",
            "close": "(`)",
            "style": "single_quote",
            "scopes": ["string.interpolated.ruby", "string.interpolated.backtick.shell"],
            "language_filter": "whitelist",
            "language_list": ["Ruby", "Shell-Unix-Generic"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        // Regex for different Languages
        {
            "name": "jsregex",
            "open": " *(/)",
            "close": "(/)[igm]*",
            "style": "regex",
            "scopes": ["string"],
            "language_filter": "whitelist",
            "language_list": ["JavaScript"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        {
            "name": "perlregex",
            "open": "(?:m|s|tr)(.|\n)",
            "close": "(.|\n)(?:[igmos]*)",
            "style": "regex",
            "scopes": ["string.regexp"],
            "language_filter": "whitelist",
            "language_list": ["Perl"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        {
            "name": "rubyregex",
            "open": " *(/)",
            "close": "(/)[imxo]*",
            "style": "regex",
            "scopes": ["string"],
            "language_filter": "whitelist",
            "language_list": ["Ruby", "RSpec", "Better RSpec"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        // Markdown
        {
            "name": "mditalic",
            "open": "(\\*|_)",
            "close": "(\\*|_)",
            "style": "default",
            "scopes": ["markup.italic"],
            "language_filter": "whitelist",
            "language_list": ["Markdown", "Multimarkdown", "GithubFlavoredMarkdown", "Markdown Extended"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        {
            "name": "mdbold",
            "open": "(\\*\\*|__)",
            "close": "(\\*\\*|__)",
            "style": "default",
            "scopes": ["markup.bold"],
            "language_filter": "whitelist",
            "language_list": ["Markdown", "Multimarkdown", "GithubFlavoredMarkdown", "Markdown Extended"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        {
            "name": "mdcodeinline",
            "open": "(`+)",
            "close": "(`+)",
            "style": "default",
            "scopes": ["markup.raw.inline.markdown"],
            "language_filter": "whitelist",
            "language_list": ["Markdown", "Multimarkdown", "GithubFlavoredMarkdown", "Markdown Extended"],
            "sub_bracket_search": "true",
            "plugin_library": "bh_modules.mdcode",
            "enabled": true
        },
        {
            "name": "mdcodeblock",
            "open": "\\s*(`{3,}|~{3,})",
            "close": "(`{3,}|~{3,})\\n?",
            "style": "default",
            "scopes": ["markup.raw.block.fenced.markdown, markup.raw.block.markdown.fenced"],
            "language_filter": "whitelist",
            "language_list": ["Markdown", "Multimarkdown", "GithubFlavoredMarkdown", "Markdown Extended"],
            "plugin_library": "bh_modules.mdcode",
            "sub_bracket_search": "true",
            "enabled": true
        },
        // LaTeX
        {
            "name": "latexmath_inline",
            "open": "(\\$)",
            "close": "(\\$)",
            "style": "default",
            "scopes": ["string.other.math.tex", "meta.environment.math.inline.dollar.latex"],
            "language_filter": "whitelist",
            "language_list": ["LaTeX", "LaTeX (TikZ)", "knitr (Rnw)"],
            "sub_bracket_search": "true",
            "enabled": true
        }
    ],

    // Rule definitions for finding and matching brackets.
    // Brackets are found by using regex and can use scope
    // qualifiers exclude certain matches.
    // Once all matches are found, the closest pair surrounding
    // the cursor are selected.
    "brackets": [
        // Basic brackets
        {
            "name": "curly",
            "open": "(\\{)",
            "close": "(\\})",
            "style": "curly",
            "scope_exclude": [
                "string",
                "comment",
                "source.regexp constant.character.escape",
                "source.yaml-tmlanguage constant.character.escape"
            ],
            "scope_exclude_exceptions": ["text.tex string.other.math"],
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex"],
            "find_in_sub_search": "true",
            "ignore_string_escape": true,
            "enabled": true
        },
        {
            "name": "round",
            "open": "(\\()",
            "close": "(\\))",
            "style": "round",
            "scope_exclude_exceptions": [
                "text.tex string.other.math",
                "punctuation.definition.string.begin.shell",
                "punctuation.definition.string.end.shell"
            ],
            "scope_exclude": [
                "string",
                "comment",
                "source.regexp constant.character.escape",
                "punctuation.definition.case-pattern.shell",
                "source.yaml-tmlanguage constant.character.escape"
            ],
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex", "RTF"],
            "find_in_sub_search": "true",
            "ignore_string_escape": true,
            "enabled": true
        },
        {
            "name": "square",
            "open": "(\\[)",
            "close": "(\\])",
            "style": "square",
            "scope_exclude": [
                "string",
                "source.regexp constant.character.escape",
                "comment"
            ],
            "scope_exclude_exceptions": ["text.tex string.other.math", "source.yaml-tmlanguage meta.value -constant.character.escape"],
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex", "RTF"],
            "find_in_sub_search": "true",
            "ignore_string_escape": true,
            "enabled": true
        },
        // PHP Angle
        {
            "name": "php_angle",
            "open": "(<\\?)(?:php)?",
            "close": "(\\?>)",
            "style": "angle",
            "scope_exclude": ["string", "comment", "keyword.operator"],
            "language_filter": "whitelist",
            "language_list": ["HTML", "HTML 5"],
            "enabled": true
        },
        // Angle
        {
            "name": "angle",
            "open": "(<)(?=[^?%]|$)",
            "close": "(?:(?<=[^?%])|(?<=^))(>)",
            "style": "angle",
            "scope_exclude": [
                "string",
                "comment",
                "keyword.operator",
                "source.ruby.rails.embedded.html",
                "source.ruby.embedded.html",
                "storage.type.function.arrow.js",
                "punctuation.accessor.php"
            ],
            "language_filter": "whitelist",
            "language_list": [
                "HTML",
                "HTML 5",
                "XML",
                "PHP",
                "HTML (Rails)",
                "HTML (Jinja Templates)",
                "HTML (Jinja2)",
                "HTML (Twig)",
                "HTML (Django)",
                "HTML+CFML",
                "ColdFusion",
                "ColdFusionCFC",
                "laravel-blade",
                "blade",
                "Handlebars",
                "AngularJS",
                "Java Server Pages (JSP)"
            ],
            "plugin_library": "bh_modules.tags",
            "enabled": true
        },
        // CSSedit groups
        {
            "name": "cssedit_groups",
            "open": "(/\\* *@group .*\\*/)",
            "close": "(/\\* *@end *\\*/)",
            "style": "default",
            "scope_exclude": [],
            "language_filter": "whitelist",
            "language_list": ["CSS"],
            "enabled": true
        },
        // Ruby embedded HTML
        // !!! May conflict with 'php_keywords' if enabled in same file !!!
        {
            "name": "ruby_embedded_html",
            "open": "((?:(?<=<%)|(?<=^)|(?<==)|(?<=<<))\\s*\\b(?:if|begin|case)\\b(?!:)|(?:(?<=<%)|(?<=^))\\s*(?:(?:private|public|protected)\\s*)?def\\b[\\p{Ll}\\p{Lu}]*\\b(?!:)|(?:(?<=<%)|(?<=^))\\s*\\b(?:for|until|unless|while|class|module)\\b(?!:)|(?<!:)\\bdo\\b(?!:))",
            "close": "(?<=[\\s;])(end)\\b(?!:)",
            "style": "default",
            "scope_exclude": ["text.html", "source", "comment", "string"],
            "scope_exclude_exceptions": [
                "source.ruby.rails.embedded.html -comment -string",
                "source.ruby.embedded.html -comment -string"
            ],
            "plugin_library": "bh_modules.rubykeywords",
            "language_filter": "whitelist",
            "language_list": ["HTML", "HTML 5", "HTML (Rails)"],
            "enabled": true
        },
        // Ruby conditional statements
        {
            "name": "ruby",
            "open": "((?:(?<=^)|(?<==)|(?<=<<))\\s*\\b(?:if|begin|case)\\b(?!:)|^\\s*(?:(?:private|public|protected)\\s*)?def\\b[\\p{Ll}\\p{Lu}]*\\b(?!:)|^\\s*\\b(?:for|until|unless|while|class|module)\\b(?!:)|(?<!:)\\bdo\\b(?!:))",
            "close": "(?<=[\\s;])(end)\\b(?!:)",
            "style": "default",
            "scope_exclude": ["string", "comment"],
            "plugin_library": "bh_modules.rubykeywords",
            "language_filter": "whitelist",
            "language_list": ["Ruby", "RSpec", "Better RSpec", "Ruby on Rails"],
            "enabled": true
        },
        // C/C++ compile switches
        {
            "name": "c_compile_switch",
            "open": "(\\#(?:if|ifdef|ifndef))\\b",
            "close": "(\\#endif)\\b",
            "style": "c_define",
            "scope_exclude": ["string", "comment"],
            "language_filter": "whitelist",
            "language_list": ["C++", "C", "Objective-C", "CCpp", "C Improved"],
            "enabled": true
        },
        // PHP conditional keywords
        // !!! May conflict with 'ruby_embedded_html' if enabled in same file !!!
        {
            "name": "php_keywords",
            "open": "(?:(?<=^)|(?<=<\\?php)|(?<=<\\?))\\s*(if|foreach|for|while|switch)\\b(?=.*?\\)\\s*:\\s*(?://.*?|/\\*.*?\\*/\\s*?)?(?:\\?>|$))",
            "close": "(?:(?<=^)|(?<=<\\?php)|(?<=<\\?))\\s*(endif|endfor|endforeach|endwhile|endswitch)\\b(?=\\s*(?:;|;?\\?>))",
            "style": "default",
            "language_filter": "whitelist",
            "scope_exclude": ["string", "comment", "text.html"],
            "scope_exclude_exceptions": [
                "source.php -comment -string"
            ],
            "plugin_library": "bh_modules.phpkeywords",
            "language_list": [
                "HTML",
                "HTML 5",
                "PHP",
                "HTML+CFML",
                "ColdFusion",
                "ColdFusionCFC"
            ],
            "enabled": true
        },
        // Erlang conditional statements
        {
            "name": "erlang",
            "open": "\\s*(\\b(?:if|case|begin|try|fun(?=\\s*\\()|receive)\\b)",
            "close": "\\b(end)\\b",
            "style": "default",
            "scope_exclude": ["string", "comment"],
            "language_filter": "whitelist",
            "plugin_library": "bh_modules.lowercase",
            "language_list": ["Erlang", "HTML (Erlang)"],
            "enabled": true
        },
        //Bash
        {
            "name": "bash",
            "open": "(?:(?<!\\\\\\n)(?:;|^|&|\\|)\\s*)\\b(if|case|while|select|until|for)\\s",
            "close": "(?:(?<!\\\\\\n)(?:;|^)\\s*)\\b(fi|esac|done)(?=;|\\s|$)",
            "style": "default",
            "scope_exclude": ["string", "comment"],
            "plugin_library": "bh_modules.bashsupport",
            "language_filter": "whitelist",
            "language_list": ["Shell-Unix-Generic"],
            "enabled": true
        },
        //Fish shell
        {
            "name": "fish",
            "open": "(?:(?<!\\\\\\n)(?:;|^|&|\\||and|or|not)\\s*)\\b(begin|if|while|for|switch|function)(?:;|\\s)",
            "close": "(?:(?<!\\\\\\n)(?:;|^)\\s*)\\b(end)(?=;|\\s|$)",
            "style": "default",
            "scope_exclude": ["string", "comment"],
            "language_filter": "whitelist",
            "language_list": ["fish"],
            "enabled": true
        },
        // Lua
        {
            "name": "lua",
            "open": "(?:(?<=[\\s;])|(?<=^))(if|while|function|do|repeat)\\b",
            "close": "(?:(?<=[\\s;])|(?<=^))(end|until)\\b",
            "style": "default",
            "scope_exclude": ["string", "comment"],
            "plugin_library": "bh_modules.luakeywords",
            "language_filter": "whitelist",
            "language_list": ["Lua"],
            "enabled": true
        },
        // LaTeX
        {
            "name": "latexenv",
            "open": "(\\\\begin{[^}]*})",
            "close": "(\\\\end{[^}]*})",
            "style": "tag",
            "scope_exclude": ["comment"],
            "plugin_library": "bh_modules.latexenvironments",
            "language_filter": "whitelist",
            "language_list": ["LaTeX", "LaTeX (TikZ)", "knitr (Rnw)"],
            "sub_bracket_search": "true",
            "enabled": true
        },
        // Pascal
        {
            "name": "pascal",
            "open": "(?:(?<=^)|(?<=[\\s;]))(try|(?<=\\=\\s)(?:class|record|interface)|begin|repeat)\\b",
            "close": "(?<=[\\s;])(end(?=[;\\s])|until(?=\\s))",
            "style": "default",
            "scope_exclude": ["string", "comment"],
            "plugin_library": "bh_modules.pascalkeywords",
            "language_filter": "whitelist",
            "language_list": ["Pascal"],
            "enabled": true
        },
        // Elixir
        {
            "name": "elixir",
            "open": "\\b(do$|fn)\\b",
            "close": "\\b(end)\\b",
            "style": "default",
            "scope_exclude": ["string", "comment"],
            "language_filter": "whitelist",
            "language_list": ["Elixir"],
            "enabled": true
        },
        // CMake
        {
            "name": "cmake",
            "open": "\\b(foreach|function|if|macro|while)\\b",
            "close": "\\b(end(?:foreach|function|if|macro|while))\\b",
            "style": "default",
            "scope_exclude": ["-keyword.cmake"],
            "plugin_library": "bh_modules.cmakekeywords",
            "language_filter": "whitelist",
            "language_list": ["CMake"],
            "enabled": true
        },
        // SINUMERIK 840D SL G-Code
        {
            "name": "s840d_gcode",
            "open": "\\b(IF(?!.*GOTO)|FOR|WHILE|REPEAT(?!.*GOTO))\\b",
            "close": "\\b(END(?:IF|FOR|WHILE)|UNTIL)\\b",
            "style": "tag",
            "scope_exclude": ["string", "comment"],
            "plugin_library": "bh_modules.s840d_gcode",
            "language_filter": "whitelist",
            "language_list": ["s840d_gcode"],
            "enabled": true
        },
        // SINUMERIK 840D SL RunMyHmi
        {
            "name": "s840d_hmi",
            "open": "^\\s*(//[ABGMS]|ACTIVATE|CHANGE|FOCUS|IF|LOAD|UNLOAD|OUTPUT|PRESS|SUB)\\b",
            "close": "^\\s*(//END|END_(?:ACTIVATE|CHANGE|FOCUS|IF|LOAD|UNLOAD|OUTPUT|PRESS|SUB))\\b",
            "style": "tag",
            "scope_exclude": ["string", "comment"],
            "plugin_library": "bh_modules.s840d_hmi",
            "language_filter": "whitelist",
            "language_list": ["s840d_hmi"],
            "enabled": true
        }
    ],

    // user_scope_brackets and user_brackets will be appended
    // to the tail of scope_brackets and brackets respectively
    // If you have custom rules that you don't want to commit to
    // the official list, and do not need to be inserted before
    // one of the official definitions, this is a good place to
    // put yours rules and keep in sync with the defaults.
    "user_scope_brackets": [],
    "user_brackets": [],

    // Define region highlight styles
    // solid, outline, underline, none, thin_underline
    // squiggly, stippled
    "bracket_styles": {
        // "default" and "unmatched" styles are special
        // styles. If they are not defined here,
        // they will be generated internally with
        // internal defaults.

        // "default" style defines attributes that
        // will be used for any style that does not
        // explicitly define that attribute.  So if
        // a style does not define a color, it will
        // use the color from the "default" style.
        "default": {
            "icon": "dot",
            // BH1's original default color for reference
            // "color": "entity.name.class",
            "color": "brackethighlighter.default",
            "style": "underline"
        },

        // This particular style is used to highlight
        // unmatched bracket pairs.  It is a special
        // style.
        "unmatched": {
            "icon": "question",
            "color": "brackethighlighter.unmatched",
            "style": "outline"
        },
        // User defined region styles
        "curly": {
            "icon": "curly_bracket",
            "color": "brackethighlighter.curly",
            "style": "outline"
        },
        "round": {
            "icon": "round_bracket",
            "color": "brackethighlighter.round",
            "style": "underline"
        },
        "square": {
            "icon": "square_bracket",
            "color": "brackethighlighter.square",
            // "style": "underline"
        },
        "angle": {
            "icon": "angle_bracket",
            "color": "brackethighlighter.angle",
            // "style": "underline"
        },
        "tag": {
            "icon": "tag",
            "color": "brackethighlighter.tag",
            // "style": "underline"
        },
        "c_define": {
            "icon": "hash",
            "color": "brackethighlighter.c_define",
            // "style": "underline"
        },
        "single_quote": {
            "icon": "single_quote",
            "color": "brackethighlighter.quote",
            // "style": "underline"
        },
        "double_quote": {
            "icon": "double_quote",
            "color": "brackethighlighter.quote",
            // "style": "underline"
        },
        "regex": {
            "icon": "regex",
            "color": "brackethighlighter.quote",
            // "style": "underline"
        }
    }
}
```

**Comment by facelessuser** [comment] 2017-12-04 20:42
You shouldn't copy `brackets`, `scope_brackets`, or `bracket_styles`.  Instead, you should use `user_brackets`, `user_scope_brackets`, and `user_bracket_styles` to only override the rule you need to, and only the specific parameters in that rule as you need.  Check out the documentation on customizing brackets.  When you override a bracket rule, you won't see updates/fixes to that rule because you are overriding it, so only override what you need, and check after updates to see what you are still overriding.

**Comment by facelessuser** [comment] 2017-12-04 20:43
As there is no bug or actionable item on this, I will close this issue.

**Closed by facelessuser** 2017-12-04 20:43 UTC
Labels: Discussion, Works as Expected
