### ISSUE TITLE
Issue with PHP Object Operator and matching

### ISSUE THREAD

**Issue by swashata** [facelessuser/BracketHighlighter#418] opened 2017-06-15 08:01 UTC
## Description

When we use the PHP Object operator like `$this->do_something();` then the wrapping brackets do not highlight properly. If we remove the arrow `->` then it starts working again.

## Support Info

- ST ver.: 3136
- Platform: windows
- Arch: x64
- Plugin ver.: 2.24.1
- Install via PC: True
- mdpopups ver.: 2.0.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Have this snippet in sublimetext

```php
<?php

class BracketHighlighterIssue {
	public function tabs( $tabs, $collapsible = false, $vertical = false ) {
		// Some code here
		?>
	<?php foreach ( $tabs as $tab ) : ?>
		<?php
		if ( ! $this->check_callback( $tab['callback'] ) ) {
			$tab['callback'] = array(
				array( $this, 'msg_error' ), array( __( 'Invalid Callback', 'wpq-sp' ) ),
			);
		}
		?>
		<div id="<?php echo $tab['id']; ?>" class="<?php echo implode( ' ', $tab_classes ); ?>">
			<?php call_user_func_array( $tab['callback'][0], $tab['callback'][1] ); ?>
			<?php $this->clear(); ?>
		</div>
	<?php endforeach; ?>
		<?php
		// Some code here
	}
}
```

2. Now you can see that under line 9, the brackets of the `if` statement doesn't highlight properly.

![screen-1](https://user-images.githubusercontent.com/1623381/27171107-ff04d8c0-51cd-11e7-9629-9ea30b06382f.gif)

3. But if we remove the object operator arrow, then it works again.

![screen-2](https://user-images.githubusercontent.com/1623381/27171121-0cff8646-51ce-11e7-8a35-bc27fe0d094b.gif)

4. Sometimes it shows `Matching Bracket Not Found` error.

![screen-3](https://user-images.githubusercontent.com/1623381/27171130-144d97bc-51ce-11e7-8fbc-eeb4740613a1.gif)

5. It also stops `<?php foreach ( ... ) : ?> /* ... */ <?php endforeach; ?>` type tags from being highlighted. But if we remove the operator tag then it starts working.

![screen-4](https://user-images.githubusercontent.com/1623381/27171271-a040e012-51ce-11e7-954d-c0e8fbb14c49.gif)

Do let me know if more information is needed.

My Preferences if needed

```json
{
	"always_show_minimap_viewport": true,
	"auto_complete": true,
	"auto_complete_commit_on_tab": true,
	"bold_folder_labels": true,
	"caret_extra_bottom": 1,
	"caret_extra_top": 1,
	"caret_extra_width": 1,
	"caret_style": "blink",
	"close_windows_when_empty": true,
	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Tomorrow.tmTheme",
	"css.gradient.fallback": true,
	"default_font_size": 12,
	"detect_indentation": false,
	"disable_tab_abbreviations": true,
	"ensure_newline_at_eof_on_save": true,
	"fade_fold_buttons": false,
	"font_face": "Consolas",
	"font_size": 14,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"ColorHelper",
		"GitGutter",
		"IntelliDocs",
		"JavaScript",
		"Vintage",
		"WordPress Completions"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"indent_to_bracket": true,
	"line_padding_bottom": 4,
	"line_padding_top": 4,
	"match_brackets": false,
    "match_brackets_angle": false,
    "match_brackets_braces": false,
    "match_brackets_content": false,
    "match_brackets_square": false,
    "match_tags": false,
	"overlay_scroll_bars": "enabled",
	"rulers":
	[
		80
	],
	"save_on_focus_lost": false,
	"shift_tab_unindent": true,
	"show_definitions": false,
	"show_encoding": true,
	"show_line_endings": true,
	"sublimelinter_popup_errors_on_save": true,
	"tab_size": 4,
	"theme": "Boxy Tomorrow.sublime-theme",
	"theme_accent_sky": true,
	"theme_bar": true,
	"theme_dirty_materialized": true,
	"theme_scrollbar_colored": true,
	"theme_scrollbar_line": true,
	"theme_sidebar_folder_mono": true,
	"theme_tab_arrows_hidden": true,
	"theme_tab_line_size_lg": true,
	"theme_tab_selected_transparent": true,
	"theme_tab_selected_underlined": true,
	"theme_tab_size_lg": true,
	"translate_tabs_to_spaces": false,
	"trim_automatic_white_space": true,
	"trim_trailing_white_space_on_save": true,
	"word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?"
}
```

**Comment by facelessuser** [comment] 2017-06-15 12:29
This is a duplicate of https://github.com/facelessuser/BracketHighlighter/issues/417 and is already fixed on master: https://github.com/facelessuser/BracketHighlighter/commit/87c7f1ee343c141a0585974eb6c595cb5c870e69.

This is due to recent changes in the default PHP syntax (I am assuming that is what you are using).  Next release will fix this.  Release is scheduled for the end of the week.

Thanks for reporting.

**Closed by facelessuser** 2017-06-15 12:29 UTC
Labels: Duplicate

**Comment by swashata** [comment] 2017-06-15 15:46
Yes that is correct. Sorry for the duplicate. I was searching with `Object Operator` :( You are right about the changes in default PHP syntax as this is exactly what I am using.

It is great to know that you have resolved this. Would be waiting for the release.

**Comment by facelessuser** [comment] 2017-06-15 15:47
Went ahead and release it.

**Comment by jsieler** [comment] 2017-11-01 10:37
Is it possibe that the issue still exists? Using last version of ST and BH from Package Control. Some brackets are still not highlited, and it looks like that ">" cause the problem.

**Comment by facelessuser** [comment] 2017-11-02 17:17
If you have an issue, please open an issue following the template giving details. I don't specifically use PHP, so depending on what the issue is, it may be required that a pull request is needed.

Syntax files get updated, and can possibly break things that used to work. But this issue was resolved whether or not it has resurfaced for a new reason. I also have no info on versions or syntax files you are using etc. But don't post that here; create a new issue.

**Comment by swashata** [comment] 2017-11-03 03:40
@facelessuser I have added the following scope to the exclusion list and it started working. `punctuation.accessor.arrow.php`. Do I need to send in a pull request?
