### ISSUE TITLE
Highlighting Suddenly Stopped Working (all syntaxes)

### ISSUE THREAD

**Issue by cheestudio** [facelessuser/BracketHighlighter#561] opened 2020-07-30 21:58 UTC
## Description

All bracket highlighting stopped working across the board! Not much more I can say; it's like the plugin isn't activated, but it clearly is. I've gone through the settings, but they look correct (and I don't think I've ever even modified them from the defaults in the first place). Default highlighting in Sublime Text works (which I've had to revert to in the meantime).

## Support Info

- ST ver.: 3211
- Platform: windows
- Arch: x64
- Plugin ver.: 2.28.0
- Install via PC: True
- mdpopups ver.: 3.7.2
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

I've uninstalled BracketHighlighter and re-installed numerous times. No reboot of Sublime or the PC will bring any highlighting back. I'm stumped, because it was literally an overnight shift and I wasn't doing anything differently. The only thing I haven't done is remove Sublime Text entirely, which seems heavy handed.

**Comment by facelessuser** [comment] 2020-07-30 22:04
The last update was 22 days ago. If you are just now seeing an issue, it is likely due to something in your personal environment.

You could look in the console, and if you see any BracketHighlighter tracebacks, post them here, but I suspect it is something in your environment. Either another plugin or your Sublime install.

As you appear to be on Windows, I'd try installing the portable version and then install BH, if it works there, it is most likely a problem with your Sublime install. If so, I'd recommend doing a revert https://www.sublimetext.com/docs/3/revert.html. You could potentially start disabling other plugins as well 🤷 .

As I use BH on my computers every day (Windows and macOS -- sometimes Linux), and I'm seeing absolutely no issues, unless I see some kind of info I can look into, I can only assume this is an issue specific to your environment and not an issue in BH.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by cheestudio** [comment] 2020-07-30 22:25
Sorry for the confusion about timing; this started after the latest patch. I just have been too busy to post a message about it! I usually close out the update notifications rather quickly, but I do recall seeing one for BH and realized shortly it wasn't working. I figured it would solve after a reboot, but it never returned.

I have an entirely different PC and the same thing is happening on that install, as well.

Console isn't showing anything negative regarding BH. I was really hoping to avoid a complete wipe of ST and plugins. I totally understand that if you're not able to replicate, then trying to fix something that's not seemingly broken is impossible. Just so weird it suddenly stopped on both PCs and I wasn't sure where to turn (besides for the whole "turn it off and on again" approach of starting clean).

**Comment by facelessuser** [comment] 2020-07-30 23:21
As I mentioned, I've been running with the last patch for the entire time, on multiple platforms. It is most likely specific to your system and not a problem with BH.

I'd try out the portable Windows version of Sublime and install only BH. It will most likely work fine (after a restart).

**Comment by facelessuser** [comment] 2020-08-02 00:24
As this is not reproducible on my end, and I have no info I can work off of in this issue to try and debug, there is nothing I can do. Closing this issue.

**Closed by facelessuser** 2020-08-02 00:24 UTC
Labels: T: support
