### ISSUE TITLE
Cant get it to work even after reading manual about changing settings to disable Sublime brackets package.

### ISSUE THREAD

**Issue by kangarooo** [facelessuser/BracketHighlighter#403] opened 2017-03-08 01:32 UTC
First couldnt find it. Then found after adding 2 more times package and restarting sublime could find it. https://packagecontrol.io/installation

Maybe sublime relists all slow? I thought they this one was supposed to be already added.

Now i installed and this is all i see- i even changed settings as seen in 2nd screenshot witch plugin doesnt do automatically for it to work but needed to change manually i still cant get all to look like in screenshot of this package. Heres screenshots how it looks and that still cant get all to work (not as in screenshots) even after making thouse needed changes in settings.

![brackets222](https://cloud.githubusercontent.com/assets/73187/23686016/d73b3742-03af-11e7-8ef0-e209947739d6.JPG)
![brackeeets](https://cloud.githubusercontent.com/assets/73187/23686017/d73be552-03af-11e7-96db-e3657b6adf5e.JPG)

**Comment by facelessuser** [comment] 2017-03-08 01:43
I'm going to need you to follow the template (https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md) for me to address your problem.  Please read the contribution guidelines to also get more info on what I am looking for: thhttp://facelessuser.github.io/BracketHighlighter/contributing/#bug-reports.  I didn't mention this in the last issue as you weren't even able to install the plugin.  Please update the opening post.

**Comment by kangarooo** [comment] 2017-03-08 02:47
That was one issue. This is another. That one works. This one is not showing blocks like in screenshot. Is my screenshot correct?
I have installed Sublime 3 on windows 10 yesterday coming from atom. Today installing plugins.
- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.23.3
- Install via PC: True
- mdpopups ver.: 1.13.1
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment] 2017-03-08 02:53
Your description of the problem is very vague.  Please describe in detail what you are wanting that you aren't seeing.

Please also read the documentation as they may answer your question.

**Comment by facelessuser** [comment] 2017-03-24 04:24
Since I haven't received anymore clarification on the issue you are having, I will have to close this issue.

**Closed by facelessuser** 2017-03-24 04:24 UTC
Labels: Insufficient Details, Invalid
