### ISSUE TITLE
Matching open or close bracket often not highlighted

### ISSUE THREAD

**Issue by jbslettebak** [facelessuser/BracketHighlighter#559] opened 2020-07-10 21:15 UTC
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request.

---

## Description

The package seems to work very well when the opening tag is not very many lines away from the closing tag. However, it happens quite often that when I have many nested divs, when clicking on the very first div, it does not highlight the matching closing div at the bottom of the document. This is also true with many of the nested divs that also have a fair amount of code within them and therefore a fair amount of lines separating the opening and closing tag. However, I generally do not have more than 300 lines in the sheets where this issue is occurring (and often much less than that), so it would surprise me if the issue is the space between the opening and closing tag. I've also noticed that this issue is most often present when the corresponding opening/closing tag is not visible on the screen at it's current position.

A similar and related issue that I've run into, is that sometimes I can click on a closing tag and be shown the opening tag, but if I were to click on that same opening tag first, I am not shown the closing tag. It seems to only work in one direction sometimes.  

Is there something that I need to change within the settings to fix this issue? Any help or suggestions would be much appreciated. 

...

> Run the following command from the menu: `Preferences->Package Settings->BracketHighlighter->Support Info`.  Post the result here.

- ST ver.: 3207
- Platform: osx
- Arch: x64
- Plugin ver.: 2.28.0
- Install via PC: True
- mdpopups ver.: 3.7.1
- backrefs ver.: 3.5
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

- See the following code as an example. If you are to click on the div class="col-sm-10" on line 12, div class="row menu-content-row" on line 13, or div class="col-sm-7 left-menu-col" on line 17, you will see that the closing tags are not highlighted. However, if you go to the closing div on line 82 you will see that by clicking on it, the opening div class="col-sm-7 left-menu-col" is highlighted. 

<?php get_header(); ?>
	<div class="content-wrapper-full secondary-page">
		<div class="container padding-full-large">
            <div class="row main-content-row">
                <div class="col-sm-2 sidebar-menu-col">
                    <div class="main-menu-wrapper">
                        <div class="menu-top-spacer">&nbsp;</div>
<?php if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar("main-menu") ) : ?>
<?php endif; ?>		                        
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="row menu-content-row">
<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>

<?php the_content(); ?>
                        <div class="col-sm-7 left-menu-col">
                            <div id="specialty-sandwiches" class="menu-title specialty-sandwiches-title"></div>
                            <table class="specialty-sandwiches-table menu-table">
                                <tbody>
    <?php
    $specialty_sandwich_header = get_field('specialty_sandwiches_header');
    if ( $specialty_sandwich_header ) { ?>
                                    <tr class="subheader-row">
                                        <td class="subheader specialty-sandwich-subheader"><?php echo $specialty_sandwich_header; ?></td>
                                    </tr>
                                    <tr>
    <?php } 
    if( have_rows('specialty_sandwiches') ):
        while ( have_rows('specialty_sandwiches') ) : the_row(); ?>
                                        <td class="specialty-sandwich-name item-name"><?php the_sub_field('specialty_sandwich_name'); ?></td>
                                        <td class="specialty-sandwich-price item-price"><?php the_sub_field('specialty_sandwich_price'); ?></td>
                                    </tr>
    <?php endwhile;
    else :
        // no rows found
    endif; ?>
    
                                </tbody>
                            </table>
                            <div id="deli" class="menu-title deli-sandwiches-title"></div>
                            <table class="deli-sandwiches-table menu-table one-col-table">
                                <tbody>
<?php 
    if( have_rows('deli_sandwiches') ):
        while ( have_rows('deli_sandwiches') ) : the_row(); ?>
                                        <td class="deli-sandwich-info item-name"><?php the_sub_field('deli_sandwiches_info'); ?></td>
                                    </tr>
    <?php endwhile;
    else :
        // no rows found
    endif; ?>                 </tbody>
                            </table>
                            <div id="burgers" class="menu-title burgers-title"></div>
                            <table class="burgers-table menu-table">
                                <tbody>
    <?php
    $burgers_header = get_field('burgers_header');
    if ( $burgers_header ) { ?>
                                    <tr class="subheader-row">
                                        <td class="subheader specialty-sandwich-subheader"><?php echo $burgers_header; ?></td>
                                    </tr>
                                    <tr>
    <?php } 
    if( have_rows('the_burgers') ):
        while ( have_rows('the_burgers') ) : the_row(); ?>
                                        <td class="burger-name item-name"><?php the_sub_field('burger_name'); ?></td>
                                        <td class="burger-price item-price"><?php the_sub_field('burger_price'); ?></td>
                                    </tr>
    <?php endwhile;
    else :
        // no rows found
    endif; ?>
    
                                </tbody>
                            </table>

                        </div>
                        <div class="col-sm-5 right-menu-col">

                        </div>
                    </div>                 
			
<?php endwhile; else: ?>
							<p><?php _e('Sorry, this page does not exist.'); ?></p>
<?php endif; ?>
                    <div class="bottom-content-row">
                        <div class="col-sm-12">
                            <div class="bottom-content-wrapper">
                                <div class="row bottom-menu-row pad-top-50 pad-bottom-20">
                                    <div class="col-sm-12">
<?php if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar("bottom-menu") ) : ?>
<?php endif; ?>
                                    </div>
                                </div>
                                <div class="row copyright-row padding-full-small">
                                    <div class="col-sm-6 copyright-col">
		<?php if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar("copyright") ) : ?>
		<?php endif; ?>
                                    </div>
                                    <div class="col-sm-6 bottom-right-wrapper">
		<?php if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar("bottom-right-text") ) : ?>
		<?php endif; ?>
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>	
<?php get_footer(); ?>

**Comment by facelessuser** [comment] 2020-08-08 15:31
I suspect this is caused by PHP preprocessor statements. But I'll verify.

**Comment by facelessuser** [comment] 2020-08-08 15:32
Also keep in mind that BH has a matching threshold for performance.  Brackets very far away will not match due to the cost of matching them (even Subime Text has a threshold in its default bracket matcher). You can adjust the threshold in the settings file.

**Comment by facelessuser** [comment] 2020-08-08 15:44
Yeah, you have a lot of tricky things due to PHP preprocessing. The problem is that you are injecting one syntax into another where one is supposed to be processed before the other, not at the same time. BH has difficulty with this.

For instance, in the following case, should the `[]` be processed first or the `{}`? If we process `[]` first, we can assume that `{}` do not match. If we process `{}` first, it'll look like only the outer `[]` match. Only if we take two passes, ignoring the other bracket type, can we match all of these.

```
[{][}]
```

In the case of HTML and PHP, PHP should be evaluated by itself, ignoring tag matching, but that isn't how BH works. And HTML tag matching should be done on the HTML once the file has been processed in HTML, because with PHP, sometimes you could have more than one valid match depending on what is in the PHP conditionals. The actual HTML output changes based on those conditionals and BH doesn't have the intelligence to realize that an opening tag may match a different ending depending on your PHP conditional, and then highlight multiple ending tags as both are correct depending on how the PHP conditional evaluates.

Hopefully, this illustrates why HTML tag matching can fall apart in PHP. BH tries to match proper tags, but the PHP preprocessor statements make certain matches look broken, so BH aborts the match.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Closed by facelessuser** 2020-08-08 15:44 UTC
Labels: S: triage
