### ISSUE TITLE
Include blank lines for align_content_highlight_bar option

### ISSUE THREAD

**Issue by comath11** [facelessuser/BracketHighlighter#460] opened 2017-11-22 19:01 UTC
## Description

I am using the "content_highlight_bar" and "align_content_highlight_bar" options, and they work great.  However, I have noticed that the highlight bar is only visible for lines that have content past the column that the current bracket is at.  That means for blank lines, the bar is not shown unless the current bracket in the first column.  I have included a screenshot below showing what this looks like.  Ideally, I would like it so the bar covers all of the lines until it reaches to the matching bracket, regardless of line length/content.  I'm looking for something similar to the [Indent Guides](https://marketplace.visualstudio.com/items?itemName=SteveDowerMSFT.IndentGuides) add on for Visual Studio.  Let me know if you need more information.

![image](https://user-images.githubusercontent.com/33137284/33144843-0702f244-cf84-11e7-80bb-6fac79e29a5d.png)

## Support Info

- ST ver.: 3143
- Platform: windows
- Arch: x64
- Plugin ver.: 2.27.0
- Install via PC: True
- mdpopups ver.: 3.2.0
- backrefs ver.: 2.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment] 2017-11-22 19:56
Duplicate of #296.  In short, this is a limitation of the SublimeText API.  See #296 for more details.

**Closed** 2017-11-22 19:56 UTC
Labels: Works as Expected
