### ISSUE TITLE
search_threshold to 50000 hangs Sublime Text several times

### ISSUE THREAD

**Issue by evandrocoan** [facelessuser/BracketHighlighter#389] opened 2016-11-20 21:13 UTC
## search_threshold to 50000 hangs Sublime Text several times

My question is, can the `BracketHighlighter` be run on a separate thread, so it cannot slow down Sublime Text?

On those thread was discussed about lagging about `BracketHighlighter`:

1. [#84](https://github.com/facelessuser/BracketHighlighter/issues/84) Significant Highlight Threshold Limits 
1. [#207](https://github.com/facelessuser/BracketHighlighter/issues/207) is bracket highlighter asynchronous? 

Recently on the package `GitGutter` the pull request:

1. [#321](https://github.com/jisaacks/GitGutter/pull/321) Introduce async invocations of git (real non-blocking behavior) (#230) 
1. [#230](https://github.com/jisaacks/GitGutter/issues/230) GitGutter causes massive lag when editing over sshfs 

It fixed the Sublime Text lag/hang for the `GitGutter`. Does it is applicable for `BracketHighlighter` to fix this lagging behavior?

For easy reproduction and to show the better the hang effects, was chose to use the multi-selection by the arrow keys, to show how the performance is degraded.

On the examples, is used a big file with a matching paren with 46000 characters length. They are my user keybinding for Sublime Text. The file showed may be found on: https://github.com/evandrocoan/SublimeTextStudio/blob/develop/User/Default%20(Windows).sublime-keymap

### Sublime Text Behavior for 500 and 50000

1. At the first part on this video is enabled the `search_threshold` to 500 and performed mouse selections from down to up, very fast. Here we may notice a very good response.
1. At the second part, is set the `search_threshold``to 50000 and performed the same mouse selections form down to up as on the first part, however Sublime Text does not respond most of the time and we got stuck.

![short_version](https://cloud.githubusercontent.com/assets/5332158/20465773/a28e1562-af4c-11e6-9b98-12bb5511d84a.gif)

### Plugin Host and Sublime Text CPU use for 500

This is a more detailed behavior from the the first part on this video just above when enabled the `search_threshold` to 500 and performed mouse selections from down to up, very fast. Here we may notice a very good response.

This was real motion gif, with 13MB, then GitHub does not allow to exceed 10MB, but it can still be see on this link: [http://i.imgur.com/102dYS5.gif](http://i.imgur.com/102dYS5.gif), just to wait it to be full loaded, before jump to performance measurement conclusions.

### Plugin Host and Sublime Text CPU use for 50000

At the second part, is set the `search_threshold` to 50000 and performed the same mouse selections from down to up as on the first part, however Sublime Text does not respond most of the time and we got stuck. We may notice when Sublime Text hangs while seeing the CPU graphic update.

We may also notice an increase CPU use both from `Plugin Host` and `Sublime Text` from the [http://i.imgur.com/102dYS5.gif](http://i.imgur.com/102dYS5.gif) just above. Most of the time here, I as pressing the key to select up and down, but `Sublime Text` just keeps hanging.
This is just a example behavior for how much it hangs. Basically `Sublime Text` is completely unusable when the `search_threshold` is set to 50000 and we are on a file where it has enough length to put the `search_threshold` to work.

Are the heavy calculations for the `search_threshold` performed on the main Sublime Text thread?
If they are not, then the calculations are so heavy the performing then using the `on_selection_modified_async` operations form `Plugin Host`? If so, they are overloading `Plugin Host`, and it is hanging `Sublime Text`. Then may then to be performed on another thread other than the `Sublime Text` and `Plugin Host`'s ones?

![search_threshold_50000](https://cloud.githubusercontent.com/assets/5332158/20465759/5d2b609c-af4c-11e6-8306-36c6bf905f7e.gif)

## Support Info
```
- ST ver.: 3126
- Platform: windows
- Arch: x32
- Plugin ver.: 2.23.0
- Install via PC: True
- mdpopups ver.: 1.11.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

## Steps to Reproduce Issue

1. Set the setting `search_threshold` to 50000
1. Underclock your CPU to 1 GHz. Make sure you got 4 CPU cores working at 1GHz.
1. To start working with sublime text on the big file as https://github.com/evandrocoan/SublimeTextStudio/blob/develop/User/Default%20(Windows).sublime-keymap with matching paren blocks within at least 46000 characters length.

If you got high speed CPU and it is perfectly responding, you may try to use a bigger file as 100000 characters for `search_threshold`. On windows the underclock is automatic for this option on the power manager: (may need a reboot to take effect)

![image](https://cloud.githubusercontent.com/assets/5332158/20466133/5c0de0d8-af54-11e6-8184-199b32d8e048.png)

**Comment by facelessuser** [comment] 2016-11-20 22:20
> 1. At the first part on this video is enabled the search_threshold to 500 and performed mouse selections from down to up, very fast. Here we may notice a very good response.
> 2. At the second part, is set the `search_threshold``to 50000 and performed the same mouse selections form down to up as on the first part, however Sublime Text does not respond most of the time and we got stuck.

This is completely expected and understood.  This will vary on machine to machine which is why in steps to reproduce you mention underclocking the CPU.  I personally use `10000` as that gives me a good distance with good performance.  Some of my faster PCs could probably take more with not to much issue, but I have found `10000` to be fine for me.

Even Sublime's builtin bracket matcher has a limit (or used to -- I haven't bothered checking recently).

The reason I don't plain on  making the actual bracket matching asynchronous is that I am referencing the view at different times while I am calculating the bracket pairs.  Since the buffer could change mid match(es), this could be very problematic.  For certain matches I have to validate by checking the syntax of matches etc.

Even if I did things asynchronously, it will still take a bit for brackets very far apart, and though you might not get the lag, you would have incorrect brackets appearing at different intervals (which would then get cleared).  Suppose I didn't just didn't show those brackets because they were now invalid, they hold us up from showing your next selected bracket as though the matching is on a separate thread, we are still only utilizing one extra thread.  The first one has to finish before I start the next.

BH tries to match during idle time.  So it is good to limit it to tasks that are reasonable for that machine to accomplish during idle time. If `50000` isn't reasonable for your machine, I would suggest using something less that is.  If I can't match the bracket in idle time, it is likely I have moved on.  When you have brackets very far apart, you can execute the search with out threshold command and find those, but you will then be prepared for the wait as you've made a purposeful effort to invoke the match, and you will wait for the result.

**Comment by facelessuser** [comment] 2016-11-20 22:41
Some further thoughts.  I'm not sure what gitgutter is doing, but if it's main implementation is to show you the status from the git app, that makes sense.  That entire process is offloaded to another thread because it doesn't need to know about the sublime view.  It is diffing the saved file against the last git revision etc.  Since I need to actually process a live view, this isn't as useful to offload.

Another plugin I wrote is ColorHelper.  I present color previews, but I do that asynchronously even though it is applying it to a live view, as I generally feel the situation lends better.  I am dealing with only text that is viewable.  I do all my syntax scope checks in one shot up front.  It's also generally okay that the previews aren't always instant.

**Comment by facelessuser** [comment] 2016-11-25 18:59
Closing this as I don't really think running the matcher through asynchronous matching will work too well do the way BH does things.  For the time being, we will stick with synchronous matching with a threshold.

**Closed by facelessuser** 2016-11-25 18:59 UTC
Labels: Won't Fix
