### ISSUE TITLE
Block type hint

### ISSUE THREAD

**Issue by alexanderadam** [facelessuser/BracketHighlighter#329] opened 2016-04-15 08:55 UTC
I presume this is a tough one because it would be strongly dependent on the context and/or language but it would be a really nice feature:

It would be nice to have a hint on the closing block element (a bracket, `end` or whatever) which gives some information about the *type* of the current block.

Something like here in the comments in the end

```ruby
RSpec.describe Something do
  describe '.some_method' do
    it 'does something' do
      lala.each do |element|
        if yet_another_end_below_this?
          something_else
        end # if
      end # each
    end # it
  end # describe
end # RSpec.describe
```

What do you think about it? Or is there already such functionality?

**Comment by facelessuser** [comment] 2016-04-15 14:17
Like a pop-up?

My opinion on this is if you are doing complex conditional nesting that span a lot of lines where the begin cannot be seen on the screen, you should be added some comments on the end as you show in your example.  Though, in the example above, current BH highlighting should be plenty in a compact piece of code as shown.

This is a duplicate of #307 which I haven't ruled out yet, but I make no promises.  I will close this in favor of #307.

**Closed by facelessuser** 2016-04-15 14:17 UTC

**Comment by alexanderadam** [comment] 2016-04-15 14:56
I thought rather to a similar visualisation like the comments. How about showing it if the particular line does not have a comment in the end?

And of course I know that you can add "real" comments indicating the relation but the problem is foreign code. You will probably find unstructured foreign code without any hints like these. And just recently somebody told me that he finds it difficult to maintain these comments.
So if you editor supports these hints natively anyway it could be easier to work with foreign code.

**Comment by facelessuser** [comment] 2016-04-15 15:33
> And just recently somebody told me that he finds it difficult to maintain these comments.

We do stuff like this in our firmware where I currently work (where it makes sense).  We mainly use it for C compiler switches, but I have seen it used at the end of long conditional blocks as well.  It isn't too difficult to maintain, but again I'm not saying everyone has to work like we do.

> I thought rather to a similar visualisation like the comments. How about showing it if the particular line does not have a comment in the end?

I am currently only interested in showing a hint when the opening (or possibly closing) isn't on the screen.  If on the screen, the opening (or closing) will be visibly highlighted making the hint not needed.  I don't think I would waste time determining if an end contains a comment if I add this.

If I do add any hints, it will probably be something quick and simple.  I don't want to add a lot of complexity that will slow down matching as it occurs on every selection and edit (well not every, but you get the idea).  At most, I will grab the opening line with maybe +1 lines of context before and after (up to X characters for each line) and show a popup next to the end highlight (or maybe vise versa if only the opening is shown).  I would not do this for multi-selections: only single selections.  I am not likely to include regex to target specific context on the opening bracket line as I don't want to learn nuances and context of all BH's supported languages as I don't use all languages and it would be slower.  If all this is still too slow, it would be limited to an on demand matching only and not be shown automatically on selection change or edit.

I haven't bothered to experiment with any of this yet, and I do't know when I would get to it, but currently it is tagged as a `maybe`.
