### ISSUE TITLE
open show_offscreen_bracket_popup with moving the caret 

### ISSUE THREAD

**Issue by stoivo** [facelessuser/BracketHighlighter#378] opened 2016-10-20 20:09 UTC
### Requirements
**Do not delete this**. Template must be followed or the issue will be marked `Invalid` and closed.

Please mark if you have done done this.  Mark by placing an `x` in the box: `- [ ]` -> `- [x]`.  Support will not be offered without this.

- [x] Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

### Description

I would like to open the popup with needing to hover over the ending or start brachet. 
These are the steps I would like to do.
- I would like to move my cursor to bracket. 
- Open `Command Palette`
- Find `BracketHighlighter: Open offscreen bracket popup` which would open the same popup.

**Comment by facelessuser** [comment] 2016-10-27 17:39
Not currently.  It is implemented as hover only at the present.

**Comment by stoivo** [comment] 2016-10-27 21:08
Is this something interesting if I implement it?

**Comment by facelessuser** [comment] 2016-10-27 22:13
Please explain in full detail how you imagine the feature working. Do you mean when (and only when) the caret is adjacent to the bracket is when the popup would be displayed?  I imagine the desire is possibly for those who are keyboard only users?  I can't really give you answer unless you layout fully how the proposed feature would work.  I could say yes, and then the feature might actually turn out not as I expect.   I just want to make sure we are on the same page.

So please explain how you envision the feature to work, and please do it using the issue template (omitt the things that don't apply -- I don't need version info for feature proposals etc.).

The issue template is probably more important for bug reports, but I've been barking at people to following the [template](https://github.com/facelessuser/BracketHighlighter/issues/371), so I kind of have to bark at everyone to make it equal.  I would just revise your opening post.

**Comment by stoivo** [comment] 2016-10-28 20:02
All I want to make it so you can have a command in command palette to open the popup. Than I can add it to al keybinding if I want to.

**Comment by facelessuser** [comment] 2016-10-28 21:19
Please read this https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md.

People often make vague feature requests or bug reports that tell me very little.  That is why I created the issue template to encourage people to think these things out before bringing me in.  From our short discussion, it is clear that I  didn't fully understand your feature proposal as your end goal wasn't fully described.

Please write up the proposal proper in the template and I will be happy to give a response.  It is a small thing that I ask.

**Comment by stoivo** [comment] 2016-10-28 22:44
I would like to open the popup with needing to hover over the ending or start brachet. 
These are the steps I would like to do.
- I would like to move my cursor to bracket. 
- Open `Command Palette`
- Find `BracketHighlighter: Open offscreen bracket popup` which would open the same popup. 

Is this more descriptive?

**Comment by facelessuser** [comment] 2016-10-28 22:51
When you created the issue, there was a template (which I pointed you to in the last post).  You deleted all the content (but you weren't supposed to), but it is stated in the template to not delete the content.  Please use the template as I require **all** to use it.  It's just my new policy to encourage people to create better issues.

Description is fine, just modify the opening post with the template and place your info under description.  If it is easier to close this issue and reopen a new issue to get the template, that is fine.

**Comment by stoivo** [comment] 2016-10-29 08:49
Is this better?

**Comment by facelessuser** [comment] 2016-10-29 14:23
Thanks for updating.  I updated the opening post with your updated description.  You didn't need version and reproduce for a feature request.  I know it may seem silly, I am just trying to get people to follow my instructions.  So I require **everyone** to follow it (even when it isn't as important), people are likely to see the pattern and follow through when it is important.  Thank you for your patience.

In answer to your question, yes I would be okay with a command that could be bound to a key mapping.  I am open to a pull request. If it turns out to be too confusing to implement cleanly, I am open to adding this feature myself.

**Comment by facelessuser** [comment] 2016-10-29 15:21
Before you get started on this.  I might want to tackle this myself.  I want to push popups to their own library.  I might want the popup to display both opening and closing bracket if both are offscreen etc.  I think I have an idea of what I want, and it may be easier for me to implement.

**Closed** 2016-10-29 16:06 UTC
Labels: Feature, Priority - Low

**Comment by facelessuser** [comment] 2016-10-29 16:08
Okay, I went ahead and refactored this to work via a command.  In the future I may make it work when the cursor isn't on the visible bracket, but just between the brackets.  And I may even may it show both brackets if both are off the screen.  But for now, it works just like hover.  It requires the cursor to be on the bracket, and then you can run the manual command.   Thanks for the suggestion.

**Comment by stoivo** [comment] 2016-10-29 21:53
Thank you so  much for the work. I deeply appreciate your work and the time you spend writing  comments. 

This is the exact behaviour I wanted to have.

**Comment by facelessuser** [comment] 2016-10-30 01:30
> Thank you so much for the work. I deeply appreciate your work and the time you spend writing comments.

Thanks.  It is always nice to hear 😄 .

**Comment by facelessuser** [comment] 2016-10-30 19:21
Looks like the next release you should be able to run the command anywhere (even when cursor is not on one of the brackets), and it will show both brackets if they are both offscreen.  When a match cannot be found, the new search without threshold link will auto_run the popup command again.  You can also feed in a `no_threshold` option in your keybinding to always execute by performing a no threshold search before attempting to show offscreen cursors.

![screenshot 2016-10-30 13 01 25](https://cloud.githubusercontent.com/assets/1055125/19839235/ac372a2c-9ea3-11e6-950f-13ba9afc6afa.png)

Still have some cleanup to do, but I like the new feature.

**Comment by facelessuser** [comment] 2016-10-30 20:08
Alright, full feature is in.

**Comment by stoivo** [comment] 2016-10-30 20:18
Awsome!

**Comment by excetara2** [comment] 2017-01-05 11:13
Is there an example keybinding for this? Do you set ``no_threshold`` to ``true``?

**Comment by excetara2** [comment] 2017-01-05 11:39
Thanks @r-stein
