### ISSUE TITLE
what is ugly tag color? 

### ISSUE THREAD

**Issue by mrG0bliN** [facelessuser/BracketHighlighter#476] opened 2018-04-02 03:37 UTC
Yesterday everything was fine, tags can be highlighted by a beautiful orange color. Now that Brown is not a beautiful color, you can fix this as?
![alt](https://image.ibb.co/dVmJAS/image.png)

**Comment by facelessuser** [comment] 2018-04-02 04:10
>  Yesterday everything was fine, tags can be highlighted by a beautiful orange color. Now that Brown is not a beautiful color, you can fix this as?

Probably related to your theme. Please see documentation to learn how to tweak the color yourself: http://facelessuser.github.io/BracketHighlighter/customize/#configuring-highlight-style.

**Comment by mrG0bliN** [comment] 2018-04-03 03:10
i dont know what happend?! Now all be fine =\
![](https://image.ibb.co/dmDFbc/image.png)

**Comment by facelessuser** [comment] 2018-04-03 14:37
@mrG0bliN, I only leave issues open if there is an actionable item that I haven't decided to ignore. As there is no actionable item here, I will be closing the issue.  Feel free to reopen if it occurs again, but only if the issue is attributable to something BracketHighlighter is doing.  Theme issues, or general Sublime issues cannot be solved by BracketHighlighter.

Also, please follow the issue template in the future, thanks.

**Closed by facelessuser** 2018-04-03 14:37 UTC
Labels: Works as Expected
