### ISSUE TITLE
ST3 Install via package control fails 

### ISSUE THREAD

**Issue by BriceShatzer** [facelessuser/BracketHighlighter#528] opened 2019-06-12 16:37 UTC
## Description
Attempt  to install BracketHighlighter via "Package Control: Install Package" command fails. 
Running the command w/ the console open produces the following: 

```
ignored packages updated to: ["BracketHighlighter", "Flow", "Markdown", "ReactJS", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'mdpopups' is not currently installed; installing...
reloading settings Packages/mdpopups/Preferences.sublime-settings
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' is not available
Package Control: The dependency 'python-jinja2' could not be installed or updated
ignored packages updated to: ["Flow", "Markdown", "ReactJS", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```
## Support Info

Sublime Text: Version 3.2.1, Build 3207
macOS Mojave 10.14.4

**Comment by jimpriest** [comment] 2019-07-01 23:17
Happening on Windows 10 as well.

**Comment by facelessuser** [comment] 2019-07-02 16:38
This is most likely a Package Control issue with maybe Bitbucket as I believe that package is failing because it is on Bitbucket.

Unfortunately, I have no control over Package Control and the process by which it delivers these dependencies, but the package currently requires them.

I'm not sure if there is an issue on Package Control dealing with this or not.

If the jinja2 package is actually no longer available, someone in the community will have to replace it as I imagine it would break multiple plugins out there.

**Comment by abhishekml121** [comment] 2019-07-04 09:43
Exactly same problem here on Sublime Version 3.2.1, Build 3207 with Ubuntu 19.04 .
@BriceShatzer  Is your problem solved ? If so then tell here and If not then what are alternative plugins related to this plugin ?

**Comment by abhishekml121** [comment] 2019-07-04 09:49
@facelessuser ...If the jinja2 package is actually no longer available, someone in the community will have to replace it as I imagine it would break multiple plugins out there.
Then what we do ?

**Comment by facelessuser** [comment] 2019-07-04 13:09
The package isn't missing though. I confirmed it the other day. You would need to bring this issue up over at Package Control.

**Comment by facelessuser** [comment] 2019-07-04 13:11
Apparently that is already an issue open for this https://github.com/wbond/package_control/issues/1435

**Comment by facelessuser** [comment] 2019-07-10 16:01
This is a package control problem as stated earlier: https://github.com/wbond/package_control/issues/1430.

You can attempt a workaround found here: https://forum.sublimetext.com/t/python-jinja2-package-install-problem/29120.

But there is nothing that I can do. This must be fixed in Package Control. I will close this issue for now as it is an upstream issue.

**Closed by facelessuser** 2019-07-10 16:01 UTC
