### ISSUE TITLE
Cursor position not updated on screen when directed by arrow keys on the keyboard

### ISSUE THREAD

**Issue by tmiquel** [facelessuser/BracketHighlighter#517] opened 2019-02-13 08:48 UTC
## Description

My screen don't update the cursor position when I move it with the keyboard arrows. This problem has arisen since I installed BH.

I click on a part of my code with my mouse, BH highlights correctly, but when I try to move the cursor with the key arrows on my keyboard, the cursor remains in its position (assigned by a click with a mouse), whereas the line hightlighted on the gutter has changed and when I type new text, this text is inserted in the new cursor positon (as directed by the keyboard arrow, but different from the cursor position as shown on the screen).

The cursor position would be correctly updated if I type something or if I perform a screenshot

## Support Info
- ST ver.: 3176
- Platform: linux
- Arch: x64
- Plugin ver.: 2.27.6
- Install via PC: True
- mdpopups ver.: 3.4.0
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. First step: Click with the mouse on a position in the code (here line 38)
![image](https://user-images.githubusercontent.com/45764690/52698355-9ccdfa80-2f73-11e9-9026-3beb14828063.png)

2. Second step Move the cursor with the position arrows (here with the down arrow to line 40, whereas the cursor remains in line 38)

![image](https://user-images.githubusercontent.com/45764690/52698585-11a13480-2f74-11e9-8cd5-8bd055aca5fa.png)

Other packages 

![image](https://user-images.githubusercontent.com/45764690/52698716-680e7300-2f74-11e9-8396-457778fb674f.png)

**Comment by facelessuser** [comment] 2019-02-13 14:27
1. I cannot reproduce this. On both Mac and Windows there is no issue. This may be only reproducing on Linux with very specific configurations.

2. BH isn't doing anything to the cursor in this scenario.

3. BH has no way of controlling Sublime's graphical refresh.

4. I would search or file an issue over at Sublime's issue tracker. There is nothing BH can do to fix this issue in your scenario. Redrawing and refreshing the UI should be properly handled by Sublime.

**Comment by facelessuser** [comment] 2019-03-06 02:29
Closing this as not reproducible.

**Closed by facelessuser** 2019-03-06 02:29 UTC
Labels: Not Reproducible
