### ISSUE TITLE
Heredoc support

### ISSUE THREAD

**Issue by Spraynard** [facelessuser/BracketHighlighter#482] opened 2018-05-01 22:30 UTC
## Description

PHP Heredocs ( <<<HTML {html} HTML; ) seem to be blocking the code going up or down to get the correct bracket. For example, here is what I see when I am trying to highlight a bracket with a HEREDOC in it.

![heredoc_fail](https://user-images.githubusercontent.com/17299952/39496539-df797bbe-4d6c-11e8-9d63-6db34db60278.png)

Is there any way to get around this ( adding exceptions and such? ) Disabling `show_unmatched` does not work for this.

## Support Info

```
- ST ver.: 3143
- Platform: linux
- Arch: x64
- Plugin ver.: 2.27.3
- Install via PC: True
- mdpopups ver.: 3.3.3
- backrefs ver.: 3.5
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```
## Steps to Reproduce Issue

1. Create a control statement ( `if` )
2. Put a HEREDOC in the control statement
3. Highlight either of the top-level control statement brackets

**Comment by facelessuser** [comment] 2018-05-01 22:35
I don't use HEREDOC, so you would need to provide me with links to syntax highlighters, copy and pasteable code example etc. before I would be able to make any workaround suggestions or explanations of what is happening here.

**Comment by Spraynard** [comment] 2018-05-03 05:28
Thanks for responding! Allow me to explain myself further. I currently just use the syntax highlighter that comes with ST3 if that helps. I'm using the "Mariana" color scheme. [I've linked to a file](http://termbin.com/wyj5) that can be copy and pasted into a ST3 window and hopefully produce the same results that I'm seeing, based on the comments that I wrote in the linked file.

**Comment by facelessuser** [comment] 2018-05-03 06:06
The issue is that the `<` in `<<<HTML` where being identified as opening angle brackets with no closing.  So it broke matching.

You can put this in your `User/bh_core.sublime-settings` file:

```js
{
    "user_brackets": [
        {
            "name": "angle",
            "scope_exclude": [
                "string",
                "comment",
                "keyword.operator",
                "source.ruby.rails.embedded.html",
                "source.ruby.embedded.html",
                "storage.type.function.arrow.js",
                "punctuation.accessor.php",
                "punctuation.accessor.arrow.php",
                "source.php meta.embedded.html punctuation.section.embedded.begin.php" // <--HEREDOC experimental fix
            ]
        }
    ]
}
```
I don't know if this introduces any side effects, so I won't make an official fix with this unless you are able to test this for a bit and determine it to be safe.

**Comment by Spraynard** [comment] 2018-05-03 20:41
Thank you! I actually work on both macOS and Ubuntu and saw that it was grabbing those "<" as brackets in the help text. Didn't show the help text when I was on Ubuntu. Anyway, I tested the same file out on example #2 and I have written down new comments on the file where I was seeing most-likely undesired behavior. [This is the link](http://termbin.com/ghwf).

**Comment by facelessuser** [comment] 2018-05-03 21:46
Did you try my suggestion above? If you override in `user_brackets` the `angle` rule's `scope_exclude` as I have above, do you still see issues?  It wasn't clear if you tried it or not.  I don't see issues on my machine, so I need to know if you are doing what I am doing.

**Comment by facelessuser** [comment] 2018-05-03 21:51
Also, I am using this on my machine for BracketHighlighters threshold:

```js
    // Character threshold to search
    "search_threshold": 10000,
```

**Comment by Spraynard** [comment] 2018-05-03 23:14
Oh yeah I meant to say that yes I did override the settings in my `bh_core.sublime_settings` file that you linked up. 

I changed the `search_threshold` to `10000` like you put up and that fixes the issue. As of right now I'd say that it works fine so I'll let you know if I find anything in my work.

**Comment by Spraynard** [comment] 2018-05-08 21:43
Hey so been working and I saw that a similar issue was happening with `<<<JAVASCRIPT` type HEREDOC. There is javascript syntax highlighting that happens on this so I'm assuming that this is a tag that ST3 would recognize. Anwyay, in order to get past that I applied a `scope_exclude` similar to your other fix: ` "source.php meta.embedded.js punctuation.section.embedded.begin.php"`

**Comment by facelessuser** [comment] 2018-05-08 21:54
Cool, let me know if you find any others, but if you don't find any more issues, we can probably patch these in the next release.

**Closed** 2019-10-25 22:49 UTC
