### ISSUE TITLE
Bracket lighter randomly crash

### ISSUE THREAD

**Issue by divinites** [facelessuser/BracketHighlighter#305] opened 2016-01-29 13:37 UTC
When start sublime text, with some probability bracket lighter does not start properly:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "bh_core in /Users/divinites/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 897, in on_activated
  File "bh_core in /Users/divinites/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 924, in ignore_event
AttributeError: 'NoneType' object has no attribute 'ignore_all'
```

**Comment by facelessuser** [comment] 2016-01-29 14:45
Can you give more details as I have never seen this issue.  The object in question gets initialized at plugin load and shouldn't ever not have that attribute. 

Was this introduced in the latest Sublime release?   What operating system is this on?

**Comment by divinites** [comment] 2016-01-29 15:31
Yes, I see the code and think that it is really weird that this object is not initialized.

I am using OS X 11, the sublime text version is 3099 (just updated, before is 3098).

This problem does not happen each time, roughly 1 time of three starts.

**Comment by facelessuser** [comment] 2016-01-29 15:38
Hmm.  I haven't updated yet,  but this kind of sounds like a new Sublime bug.  Events shouldn't get called before plugins finish loading. 

I will test it out or when I get a chance,  but if it is what I think it is,  it may be something that needs to get fixed in Sublime.

**Comment by divinites** [comment] 2016-01-29 15:42
I have tested this plug-in with version 3098, and the official release (3083), the bug that I mentioned above persists.

**Comment by facelessuser** [comment] 2016-01-29 15:53
I am not sure if there is possibly a problem occurring earlier with your BH install that later causes the failure.  To be safe, maybe run the Package Control commands "Upgrade Package" and select BracketHighlighter (if shown) and run "Satisfy Dependencies" and restart ST.  Package Control for some reason does not seem to upgrade dependencies all the time when the main package is upgraded.

The fact that this persists on 3083 is odd.  I use Sublime Text 3095 on OSX and have not yet seen the issue and I have been using both for quite a while.  I actually develop most of my plugins on OSX and they are usually very well tested on those platforms.  It may be be an issue where you need to revert: https://www.sublimetext.com/docs/3/revert.html.

It may also be possible another plugin is somehow interfering with BracketHighlighter?

Sadly I am just not seeing these issues.

**Comment by divinites** [comment] 2016-01-29 16:29
I opened the debug flag in the setting file and add a `debug("object created")` just below bh_core() object is created. I can no more replicate this bug, every time the object is correctly initialized with no problem. I will not assume that it is because I add one line debug code, since it does not make any substantial difference -- on the other hand, I think that a plausible explanation would be: after I modify the code, there is a bh_core.py in the package folder. Therefore,  every time when sublime text starts, it no more needs to extract from installed package first and load this plugin. 

Depending on the speed and process of extracting packages, sometimes it works, sometimes it does not.  From the user's angle, I thus see the randomness of trackback message. 

proposed solution: add a `.no-sublime-package` file.


Every time when sublime text starts, it will extract packages from installed package and load them. That means,

**Comment by facelessuser** [comment] 2016-01-29 17:36
> proposed solution: add a .no-sublime-package file.

I'll be honest, I doubt this is the problem.  The uninitialized object in question is contained within the same file that uses it.  The file will have to be loaded completely in memory before Python would even  process and execute it.  Unpacking is not the problem.  You could maybe argue that if it was a dependency that wasn't unpacked yet, but that isn't the case here, and I have a lot of experience with the Sublime packages and I can assure you that `.no-sublime-package` is only needed if you have something that just can't be easily accessed with the API in packaged or run from the zip.

Further, I think your issue is specific to your machine.  I imagine I would be have had a complaint long before now if zipping where the problem.  BH has been zipped for a long time under ST3 with no complaints.

Assuming the debug statement actually fixes the issue for you, I would be more inclined to think it is a timing issue then a packing issue.  But even then, I don't think that is the problem as we assign the thread object on the main thread.  We are also not using asynchronous events in the API.  Further, plugin_loaded must complete before we start events.  This is from the sublime plugin api:

```python
def on_api_ready():
    global api_ready
    api_ready = True

    for m in list(sys.modules.values()):
        if "plugin_loaded" in m.__dict__:
            try:
                m.plugin_loaded()
            except:
                traceback.print_exc()

    # Synthesize an on_activated call
    w = sublime.active_window()
    if w:
        view_id = sublime_api.window_active_view(w.window_id)
        if view_id != 0:
            try:
                on_activated(view_id)
            except:
                traceback.print_exc()
```

It really seems like there is something wrong with your specific setup.

**Comment by divinites** [comment] 2016-01-29 17:49
I have three difference macs, one Hackintosh, two Mac book pro, all of them have similar problems. I also look through all issues before and I am also surprised that no one reported this issue before.  In the mean time, I will use my modified file as a temporary workaround.

**Comment by facelessuser** [comment] 2016-01-29 18:24
Now, maybe I don't see this because I am always using a dev version that is unpacked, but again, I would have expected an issue by now.  I will try running on OSX for a week with the zipped version and see if I can reproduce, that is really all I can do at this point.  If I can't reproduce it, I can't fix it.  It is possible that there may be an additional plugin on your systems that is causing an unintended side effect, but since I don't know what else your running with, it is hard for me to know.

So let me run with BH zipped for a week or so and I will see if I can reproduce this issue.

**Comment by divinites** [comment] 2016-01-29 20:17
Thanks a lot! I appreciate your positive attitude and patience.

**Comment by facelessuser** [comment] 2016-02-09 16:37
I have not been able to reproduce this under any circumstance.  If you are able to narrow it down to something more specific, I may be able to address it, but I have restarted over and over with a zipped version of BH on Windows and OSX and cannot make it crash.  There must be some other kind of criteria or plugin or something that is causing it to crash on your system.  While, for whatever reason, adding an extra a print line may "seem" to fix the problem, I cannot justify inserting a random print statement without hard evidence of it actually fixing a problem.  Right now I cannot even confirm there is a problem.

Inserting a print statement that fixes things would make me believe there is a timing issue, but that doesn't make sense in the context of the given function in question.  I personally believe there is some other common thread on all your machines that is causing the issue, but I am not convinced yet BH is to blame.  I feel the print statement may be masking the real problem, but I have no evidence yet to suggest BH is to blame.  As I cannot reproduce this issue in any way, I can only assume this is not a BH issue.  I am very much against inserting random unexplained code without any clear understanding of how or what it is even fixing.  If down the road we are able to understand and identify a problem, then I have no problem addressing the problem with a clear understandable fix.

Sorry I cannot be of more assistance.

**Closed** 2016-02-09 16:37 UTC

**Comment by divinites** [comment] 2016-02-09 16:45
Thanks for your patience and explanation. 

I am also curious about the reason behind… When sometime the trace back information appears, BH still works after a few seconds, So bh_thread successfully initializes any way. I think that there might be some mysterious consequences that I cannot figure out at this moment. But since it does not have any substantial effect on daily usage, I will put it aside and keep an eye on it.

best wishes — T.W.

**Comment by divinites** [comment] 2016-04-30 14:37
The lastest update solved this ghost issue, Thanks for your impressive work!

**Comment by facelessuser** [comment] 2016-04-30 15:37
Latest update of Sublime or BH?  I don't think I added any fixes to this really.  I just added or improved specific language support.  Well, maybe getting a new version cleared out a corrupted cache, who knows.  Glad it's working though.

**Comment by divinites** [comment] 2016-07-08 16:18
I think that I found the reason finally.

When you click the sublime text icon to open it, when a view shows, you instantly tap "cmd + `" to show the console, then with large probability you will see this error:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "bh_core in /Users/divinites/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 1176, in on_activated
  File "bh_core in /Users/divinites/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 1207, in ignore_event
AttributeError: 'NoneType' object has no attribute 'ignore_all'
```
However, If you wait until all plugins loaded and then open the console, nothing happens.

That's why this bug seems to be random...

**Comment by facelessuser** [comment] 2016-07-08 16:24
> When you click the sublime text icon to open it, when a view shows, you instantly tap "cmd + `" to show the console, then with large probability you will see this error:

I just don't find this to be the case.  When developing, I often have to close down Sublime and reopen and check the console right away.  Though I haven't done this with with a just a zipped version of BH.    I can give it a try later tonight, but again, if I can't reproduce it, then I don't know what to say.  This sounds like more of an issue with how Sublime may load packages, but like I said, I will at least attempt to reproduce.

**Comment by divinites** [comment] 2016-07-08 16:31
Thanks. I just open and close sublime text 10 times.  with instantly openning the console 5 times, the error show 4 times; with waiting 5 seconds and openning the console 5 times, the error does not appear. I agree with you that this is probably related to how plugin_host works, but at least now I know how to avoid this. 

I appreciate your positive attitude towards this seemingly trivial bug as well.

cheers
