### ISSUE TITLE
Is there any shortcut key for jump between close and open mark? 

### ISSUE THREAD

**Issue by dotku** [facelessuser/BracketHighlighter#404] opened 2017-03-13 06:54 UTC
Eg, the HTML close and close tag?

**Comment by facelessuser** [comment] 2017-03-14 21:24
I think this is what you are looking for: https://github.com/facelessuser/BracketHighlighter/issues/405.

Please use the issue template when creating issues next time.  Thanks.

**Comment by facelessuser** [comment] 2017-03-16 17:34
Did the suggestion work for you?  If not please give a detailed instructions.  I leave issues open for about a week when waiting for additional info to determine if the issue is valid.  If I don't hear back in about a week, I usually close the issue.

**Closed** 2017-03-24 04:22 UTC
