### ISSUE TITLE
[XML] self closing tags

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/BracketHighlighter#384] opened 2016-11-13 10:28 UTC
## Description

Consider the following XML construct with a self closing tag.

```xml
<xml>
	<node attrib="value" />
</xml>
```

BracketHighlighter marks `node` invalid as it does not recognize the self closing `/>` and therefore expects a closing `</node>`

Have a look here:

![screen](https://cloud.githubusercontent.com/assets/16542113/20244883/dd83c032-a992-11e6-9798-5ca7d3e65920.png)

I am running Sublime Text 3126 with default XML package on Win10x64.

---

## Support Info
- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.22.1
- Install via PC: True
- mdpopups ver.: 1.11.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

Open the xml snippet from above.

**Comment by facelessuser** [comment] 2016-11-13 14:05
@deathaxe.  Your description is fine, but please follow the template format.  I require people to follow the template to ensure I get all the information I desire, like BH version and version of dependencies.  Please update the opening post following the template, and I'd be happy to look at this issue.  Thanks.

**Comment by facelessuser** [comment] 2016-11-15 17:03
@deathaxe, please make sure you update the issue as requested as work will not start on this issue until it is updated with the requested changes.  I will probably be making a release within the week, and any changes associated with this issue may not make it in.  It is important for me to have version info for the plugin to ensure people are seeing the issue in the very latest version with the latest dependencies etc.  I don't think you need to provide steps as you have done fine in the description.

I have a policy that if issues remain in an invalid state for a week, I close them.

**Comment by deathaxe** [comment] 2016-11-16 19:36
What template? You provide a very comprehensive description, but I do not recognize it as template nor do I get an idea where to put which information to. As package control automatically  checks for updates I am always at the latest patch level available. If not this is the first step before calling for help.

**Comment by facelessuser** [comment] 2016-11-16 19:50
> What template? 
I see you posted the template in the first post now.  But usually you would just fill out the appropriate section.  I leave info under each section to tell people what I am looking for.  You would just remove the text under the headings.

> You provide a very comprehensive description, but I do not recognize it as template nor do I get an idea where to put which information to

Is there some way I can help make it more recognizable as a template?  I'm running into the issue where if I just tell people to check out a page in the the documentation explaining what I want, people don't bother to check it.  So I try to give people everything upfront that I want in the issue template.  But maybe people are still confused they are supposed to fill out the appropriate section with what is described there?  Any insight will be helpful.  I find some people intuitively get it, but others either do not, or just choose to not follow it.  I am open to suggestions that can make it more clear what I am looking for. Thanks.

---

> I am always at the latest patch level available

In practice I found this is not the case with everyone.  And sometimes (for what ever reason) people can be on old versions.  Package Control also doesn't always do a good job of keeping dependencies up to date either, so that info is useful as well.  In the template I mention the following which is what I was looking for.

```
Run the following command from the menu: Preferences->Package Settings->BracketHighlighter->Support Info. Post the result here.
```

Anyways, I will take your word that everything is up to date.  Please in the future use the Support Info command in the menu and post the results in issues.

**Comment by facelessuser** [comment] 2016-11-16 20:03
I see you've updated the opening post.  Thanks!

If you can think of anyways to make the issue process less confusing, please do let me know.

**Comment by r-stein** [comment] 2016-11-16 20:10
@facelessuser You could replace the first sentence by "Please read and fill this template by replacing the instructions with their outcomes." This would clearify how the template is supposed to filled out.

**Comment by facelessuser** [comment] 2016-11-16 20:33
Thanks @r-stein, I will give that a try.

I've been iterating through different templates to try and not be annoying but also trying to make it clear what I expect.  I know I will never get 100% of people to comply as there will always be someone who doesn't want to do it just because you asked them to, but if people are generally making an attempt to give what is asked, I think that will be a win.

**Comment by facelessuser** [comment] 2016-11-16 20:38
As for the issue at hand.  I know what needs to be done.  I need to create to refactor the how special tags are treated.  I've been treating things improper. I will need the following moving forward:

- optional_tag setting: tags that can optionally not be closed (will not allow self closing style)
- void_tag setting: tags that never have closing (can take self closing style or not, but are always single)
- self_closing tags: Require a closing unless done in self closing style.

I will also add a new profile called `xml`, and will instead have the `xhtml` style be moved to a different profile.  I will provide a first line setting for the `xhtml` profile that will enable `xhtml` profile if we are in HTML files that start with an XML header.

I think this will clean up special tags in all formats.

**Closed** 2016-11-17 01:54 UTC
Labels: Bug, Priority - Medium

**Comment by facelessuser** [comment] 2016-11-17 02:01
The fix contains some breaking changes to `bh_tag.sublime-settings`.  This improve special tag handling quite a bit as previous logic wasn't that great, which was mainly because of my initial misunderstandings.  XML will be handled differently than XHTML (which should have been the case from the beginning).  HTML tag handling for optional, void, and self closing tags should be better now.  Unfortunately with optional tags I don't have logic determining whether the the optional tags are valid, but BH is not meant to be an HTML validator anyways.

**Comment by deathaxe** [comment] 2016-11-17 17:03
Just for clearance, I did not want to be unpolite with my comment, that's why I deleted it again. I was just a bit surprized as I did not expect to have missed something. I really had to search through the closed issues to learn what information and format you expect. The core issues clearly shows the gaps to fill. I didn't found them here and expected everything to be an description only. I know how hard it is to find the correct way to clearly document something. That's why I would suggest the following change to your current template to clearly show up gaps to fill and put descriptions in the background a little bit to make clear they are hints only.

---
# Template suggestion

Please read and fill out this template by replacing the instructions with appropriate information.  Make sure you've read: http://facelessuser.github.io/BracketHighlighter/contributing/.  If the template is not followed, the issue will be marked `Invalid` and closed.

Search past issues and read the area of the [documentation](http://facelessuser.github.io/BracketHighlighter/) related to your specific question, issue, or request. Often the answer to your question is already found there.  You may also find the feature you are requesting already exists. It is okay if after doing this you are still confused, just mention what you didn't understand in the documentation below so we can make it better.

---

## Description

...   what is the issue / request ?

> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> _For feature requests or proposals:_

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

> _For bugs and support questions:_

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

...

> Paste version information from menu: `Preferences->Package Settings->BracketHighlighter->Support Info`. 

## Steps to Reproduce Issue

1. First step
2. Second step
3. Third step

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment] 2016-11-17 17:32
> Just for clearance, I did not want to be unpolite with my comment, that's why I deleted it again.

I didn't catch anything impolite (unless I missed something you edited later).  I had no problems with our interactions.  If some how it was interpreted that I did have a problem, that was incorrect.   Apologies if I have left an impression otherwise.  I usually try to be patient unless people are rude.

Your description was very thorough and acceptable, but I did also want the version stuff.  In general I am trying to create a level of consistency.   I get so many vague issues, or things I have no idea how to reproduce, or pictures where I have to transcribe the whole picture's content by hand to reproduce the issue when they could have also just provided plain text I could copy and paste.  I hold everyone to the same requirements to encourage those who create exceptionally vague issues to give me something more I can work with so I don't have to keep bugging them for more info.

If everyone has to follow the same procedure, it becomes very clear to newcomers what I am looking for.  Like you, they can look at past issues and see.

> That's why I would suggest the following change to your current template to clearly show up gaps to fill and put descriptions in the background a little bit to make clear they are hints only.

I will take this into consideration.  Anything I can do to appropriately emphasize my expectations is appreciated.  Maybe it will make things more clear.  I will probably omit the **Suggestion** in favor of **Requirement** as that is what I actually mean :smile: .

Thanks for your contributions, they are very much appreciated.  And this was a good one that had greater implications when I looked into it further.
