### ISSUE TITLE
Feature requests to allow using your plugin from another plugin

### ISSUE THREAD

**Issue by canoeberry** [facelessuser/BracketHighlighter#395] opened 2017-01-03 21:14 UTC
## Description

You have helped me in the past by having a bh_async_key as well as a bh_key for synchronous behavior. That helped me define a command in terms of one of your commands.

I have made use of your plugin tonight inside the sublemacspro plugin. I have been meaning to do this for ages and I had good success with that tonight.

However, I encountered several issues which I wonder if you'd be willing to discuss.

1. Is there a way to stop "Jump to Right/Left Bracket" from moving outside the brackets if already at the LEFT or RIGHT end? That is, if you're already at the RIGHT side and "Jump to Right Bracket" is there a way to get it not to move?

2. I looked at the documentation and cannot figure out if I can easily add support for Ruby's backquote character. It should, as far as I know, be treated the same as a regular quoted string. I think it's easy and wonder if you can point me to the right documentation and also explain whether I can do it from within my plugin.

3. Is there an API you can expose that allows me to ask the question "is the character at point a bracket highlighter open or close tag, bracket, string?" Because if so, that would just be perfect. What I have now is not perfect (see below).

My reasons for this are to implement forward/backward s-expression for emacs. Right now I walk the buffer looking at characters, and then when I find bracket characters like one of "[{(", I invoke your code and it gets me to the other side. But what I'd really like to do is, be able to encounter a "begin" in ruby code and have it skip over to the matching "end". And currently, since my code is triggered when it encounters a "{" (for example), in Latex mode, when it encounters the "{" in \begin{equation} it actually goes to the match \end{equation} because bracket highlighter works its magic, but only because I encountered the "{".

I hope this is clear what I am looking for.

## Support Info

- ST ver.: 3125
- Platform: osx
- Arch: x64
- Plugin ver.: 2.23.1
- Install via PC: True
- mdpopups ver.: 1.12.0
- backrefs ver.: 1.0.post1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

No real steps here. Just a discussion.

**Comment by r-stein** [comment] 2017-01-03 21:47
It may be worth to mention, that you can just write your own commands and even ship them with your plugin (as long it has a consistent name).
E.g. create something based on https://github.com/facelessuser/BracketHighlighter/blob/master/bh_modules/bracketselect.py

name it `yourbracketselect` and put it in the folder `bh_modules` inside your `sublimemacspro` package. Then add a keybinding
``` js
{
    "keys": ["{"],
    "command": "bh_key",
    "args":
    {
        "no_outside_adj": null,
        "no_block_mode": null,
        "lines" : true,
        "plugin":
        {
            "type": ["__all__"],
            "command": "sublimemacspro.bh_modules.yourbracketselect",
            "args": {"select": "right"}
        }
    }
},
```

Hence you can create the behavior requested in 1. and you have most likely the information available requested at 3.

For 2. I am not familiar with rubys backtick, but in general you can add new quote types in the [settings](https://github.com/facelessuser/BracketHighlighter/blob/st3-2.23.1/bh_core.sublime-settings#L211). This is either in the user settings or in the default settings. Hence it might be the best to create a PR to add a new quote type.

**Comment by facelessuser** [comment] 2017-01-03 22:27
Yup, @r-stein is right on track with his answer.

1. Create your own.

2.  I don't know if it is "easily" added or not as I haven't looked at Ruby's backtick quote scoping (and this can vary from highlighter to highlighter, but theoretically it is possible.  Since I imagine it is a case of opening and closing scopes being identical, it is likely you would scope it like quotes, but depending on the syntax highlighter, you could search for all backticks and filter them by scope if the highlighter scopes opening and closing backticks differently.  It is tough to say without me looking into it further.  I do cover this in the docs, and there are examples.

3.  I don't know exactly what your plans are exactly, but I do store some info in the view, see here: https://github.com/facelessuser/BracketHighlighter/blob/master/bh_core.py#L978.  It's not documented as I added just for dealing with hovers if I recall.  Maybe that can help you.  There are probably different approaches you could take.

**Comment by canoeberry** [comment] 2017-01-04 09:48
Thanks to both of you for your replies. Like a little kid, these two comments kept me in a fitful sleep last night, excited about the possibilities.

My plan until now has been to walk the buffer looking for trigger characters, e.g., brackets or quotes, and then invoke either native sublime functionality or now your functionality to navigate "to the other side" of whatever was just encountered. It works better than ever now but I really want it to work properly for all bracket supported items, including HTML tags, Ruby begin/end pairs, etc.

So now I am thinking I will implement the s-expression functionality within one of your plugins entirely. I will poke around looking for more information in your docs, but I am now guessing that one of your plugins, when invoked, already has variables for the immediate surrounding, matched "brackets" in the left and right instance variables. I can now see the code which is moving beyond the right or the left in that bracketselect plugin (at least I think I see it), so I know what to do for that.

At any given time, when invoking my command, I am probably between some matching brackets, but what I need to be able to detect is when I am approaching another pair inside the initial pair. It looks like I might need to use the view setting stuff you pointed me at. Perhaps I will initialize the code from those settings by searching for the closest matched tag  in the direction and I am moving, and all will just fall into place from that.

Thanks for your help. I will report back if I have any more questions.

**Comment by canoeberry** [comment] 2017-01-04 11:17
Well, not having too much luck. Here's a test case. The cursor is at the "(", i.e., between the "n" and the "(":

    some_function("With a string argument")

1. Unless no_outside_adjacent=False, the plugin command will not actually run when the cursor is just before the "(". When it's false, the left and right values are the two parens and all is well.
2. However, if I put the cursor just before the first double-quote character, left and right are still the two parens. This is not right for me because I want it to be the quotes.

So I need False to be set in order for the command to run just outside the brackets, but then I lose the ability/fine-control to have it use the quotes when just outside the quotes. In other words, if we allow outside adjacent, we lose the ability to handle the situation when two open brackets of any type are right next to each other.

So my status is: I can definitely implement #1. I do not think I can implement #3 because the information in the view seems just to mirror the left/right values anyway. (I admit I have seen brackets that were different from left/right but I can't reproduce that at the moment for some reason.)  I don't think the plugin API allows me to move the cursor around in the plugin and having the brackets recalculated from that new position so that I can move around some more with the new information. Meanwhile, I think I can do #2 if I just learn the way to specify brackets, hopefully without clobbering the existing brackets. I saw a section on that but it wasn't crystal clear where to define things. (I am notoriously slow on the uptake though ...)

Am I missing something?

**Comment by r-stein** [comment] 2017-01-04 12:18
For 3. You would like a method to request the surrounding brackets from any point/run a search to get the bracket positions?
I don't think that is currently supported without a lot of overhead (re-implement parts of the core).

For 2. it would be something like this:

``` js
    "user_scope_brackets": [
        {
            "name": "rubybackticks",
            "open": "(`)",
            "close": "(`)",
            "style": "default",
            "scopes": ["string.interpolated.ruby"],
            "language_filter": "whitelist",
            "language_list": ["Ruby"],
            "sub_bracket_search": "true"
        },
    ]
```

**Comment by canoeberry** [comment] 2017-01-04 12:40
Thanks again.

I think it's time for me to look at the bh_core code and grok how it all works.

**Comment by canoeberry** [comment] 2017-01-04 13:36
I was able to add a definition for rubybackticks if it's not already in the settings, and that works nicely. Thanks for the tip.

I almost asked some generic questions about how this is all supposed to work, but then I remembered this [thread](https://github.com/facelessuser/BracketHighlighter/issues/207) as a result of the first time I contacted facelessuser.

Oh well. I think I got most of what I wanted. My middle ideas seems impossible and due to buffer copying, I am afraid it might never perform well enough. Perhaps a buffer window cache would be an OK approach to making it perform better, actually. Not sure about that.

**Comment by facelessuser** [comment] 2017-01-04 15:52
What is your middle idea?

**Comment by facelessuser** [comment] 2017-01-04 15:54
You should be able to handle two brackets flaking the cursor.  Do you have some code I can look at and try?

**Comment by facelessuser** [comment] 2017-01-04 15:56
Also, of you have a good working ruby backtic rule, please issue a pull.  It would mask make sense to include it here if it's working well.

**Comment by facelessuser** [comment] 2017-01-04 16:04
One thing to note.  BH, when posed with a choice of two brackets, BH always favors left for consistency.  That is probably why you are having issues with two brackets on either side.  It sounds like you would prefer a system that favors right...

**Comment by canoeberry** [comment] 2017-01-04 16:06
Oops - I misspoke when I said "middle idea" which was bullet 2 in my original request.

A general purpose API is what I really want. But short of that, a way to ask for the nearest bracket end to me that I am not current inside.

So for example, if I am

    def this_is_a_ruby_function(with, some, arguments)
        ....
    end

and my cursor is just after "def", it would be great if I could know
1. what brackets I am currently in (I think the answer is def/end and that is currently supplied as "left" and "right")
2. what are the closest bracket pairs in both directions that I am not inside, which in this case would be the "(" and ")" of the function call. I would also want that information looking backwards in the buffer. I think it is the case that you would not have to  look beyond the boundaries of the bracket pair we're already inside, which is why the answer in this case is just the forward looking "(", ")" pair.

This would allow me to walk through the buffer doing various things, but then notice when I have reached a bracket in one direction or the other, in which case I would jump to the other side of that pair.

**Comment by canoeberry** [comment] 2017-01-04 16:10
Regarding the rubybacktick rule, I just used the one supplied by @r-stein and it worked perfectly as far as I could tell with some basic testing. So that might be all you need.

I think that rule would also apply to shell scripts and perhaps many others (perl even?)

**Comment by facelessuser** [comment] 2017-01-04 16:12
I see now... And since BH doesn't really consider the next pair fully, that is where you are stuck.

Yeah, I don't really have an easy answer for that.  I would have to adjust the algorithm to always look ahead for an additional pair...

**Comment by facelessuser** [comment] 2017-01-04 16:15
> I think that rule would also apply to shell scripts and perhaps many others (perl even?)

Maybe, the scopes would probably be different for every syntax highlighter, so I would probably fold them in as each one gets tested and confirmed.

**Comment by canoeberry** [comment] 2017-01-04 16:24
Maybe not always look ahead. Maybe just do it if an argument is supplied. The interesting thing is, you probably have already encountered it while finding the matching pair that you automatically supply to the plugin.

Still catching up on your previous message about favoring left vs. favoring right.

Was I right that the plugin will not be invoked if you are not within brackets and adjacent is disallowed?

**Comment by canoeberry** [comment] 2017-01-04 16:27
I am unclear on the values for the language settings. I tried adding "Shell Script (Bash)" to the language_list value as shown above, but that is not working. "Shell Script (Bash)" is what is displayed by the editor in the lower right of the window. Meanwhile, if I try to set syntax-specific settings it says something about "Unix Shell Generic".

I wanted to supply you with the two most common backtick cases I know of.

**Comment by canoeberry** [comment] 2017-01-04 16:30
Regarding favoring left or right, the answer to that is No :-). I favor right when moving in the forward direction, and I favor left when moving in the backward direction.

Now that would be a great option to add to the plugin call, instead of the adjacent option.

**Comment by canoeberry** [comment] 2017-01-04 16:36
Here is another example:

    self.call_some_function("with a string as an argument")

If the cursor is just to the left of the "(" I want to use the parens. If the cursor is just after the "(" and sitting next to the double quote, I want to use the string boundaries.

But that is in the forward direction. In the backward direction, if the cursor is sitting just after the ")" I want it to use the parens as the bracket, but if I am just before the double quote, I want it to use the string.

Is there any chance to add a favor="left|right" option, which by its very definition means it will allow you to be NEXT to the bracket rather than inside it?

**Comment by facelessuser** [comment] 2017-01-04 17:05
What about when your bracket is between the opening square and the closing round?

```
()[]
```

**Comment by canoeberry** [comment] 2017-01-04 17:24
Luckily for me, I always want to favor in one direction or the other. Isn't that good enough?

**Comment by facelessuser** [comment] 2017-01-04 17:25
> I am unclear on the values for the language settings. I tried adding "Shell Script (Bash)" to the language_list value as shown above, but that is not working. "Shell Script (Bash)" is what is displayed by the editor in the lower right of the window. Meanwhile, if I try to set syntax-specific settings it says something about "Unix Shell Generic".

You would use the name of the syntax file, ignore the name shown by the editor.  Also, @r-stein is using this scope `"string.interpolated.ruby"`.  It is probably different for bash.

**Comment by facelessuser** [comment] 2017-01-04 17:29
> Luckily for me, I always want to favor in one direction or the other. Isn't that good enough?

If it is always a manual thing, and never expected to be auto decided, then yes.

In order to do this, I would need to add the logic to handle this reverse sense of priority.  As things get complicated to have both enabled simultaneously, this could never be implemented in the auto bracket finding.  It could only be used as either left or right priority, though you could manually switch priority.

Now, I need to think about whether this is a direction I want to go in :wink:.

**Comment by canoeberry** [comment] 2017-01-04 17:43
I have the scope for bash. So how do I find the name of the syntax file? I tried editing syntax-specific settings which gave me the unix shell generic string but that seemed not to work either.

**Comment by canoeberry** [comment] 2017-01-04 17:51
I am not sure how your stuff works, of course. But I am under the impression that you have some knowledge of where the currently applicable (based on the value of the selections) brackets are at all times. The UI displays it, you know it.

In the case of being between the () and [] below:

    ()[]

you seem to know about both, and have favored with a darker underline the () over the [].

In the case of

    method("string_argument")

you seem aware of just the parens when just before the "(" and just after the ")" and you seem aware of both the parens and the string if you're just before the ")" but not if you're just after the "(".

So that's the one thing which seems problematic at this point. Otherwise you already seem to have all the information you need, and you just need to be told which to favor.

Let me know what you decide. Things are already a lot better for me than they were before. In the meantime, I will keep trying to get the backtick working for bash shell. Once that works, should I issue a pull request?

**Comment by facelessuser** [comment] 2017-01-04 17:51
It's probably `ShellScript/Shell-Unix-Generic`.  I just used PackageResourceViewer and navigated through the packages to find it.

**Comment by facelessuser** [comment] 2017-01-04 17:56
I am only aware of brackets before and after the cursor in the moment of evaluation, then it is forgotten.  I only highlight one bracket.  You mentioned a darker underline for one over the other, but I only highlight one.  If you see another underline, it is likely you still have Sublime's highlighter enabled at the same time.

**Comment by r-stein** [comment] 2017-01-04 18:07
You can get the scopes with [ScopeHunter](https://github.com/facelessuser/ScopeHunter) and the syntax names by wrinting to the console (``ctrl+` ``) `view.settings().get("syntax")` and only use the last part before the extension.

**Comment by facelessuser** [comment] 2017-01-04 18:12
ScopeHunter will also tell you the name of the Syntax File if you have that option enabled.

**Comment by canoeberry** [comment] 2017-01-04 18:27
Now that's funny. I tried turning off built-in brackets a long time ago and again recently, but that caused some of my other plugin code to stop working. Now that I have switched to your plugin for navigating over brackets and turned off the built-in matching, I only see one set of underlines. I seriously could never understand what you were doing highlighting multiple things.

I wonder if you can store all the matched brackets you encounter while calculating the actual left and right values? I am not sure whether you keep track of existing balanced pairs as you go, but I am pretty sure that what I want is typically somewhere inside what you have already calculated is the left and right values. That's what I figured I would find in the view settings you mentioned a earlier in this thread.

**Comment by canoeberry** [comment] 2017-01-04 18:36
I got the syntax working for shell and ruby. It was the last component of the syntax name that I needed, which in this case was Unix-Shell-Generic.

I am doing this and it works.

I think I will change the name to backticks, and I think style="single_quote" is better than default.

Shall I do a pull request and place this into the bh_core.sublime_settings file?

```
            scope_brackets_settings.append({
                "name": "rubybackticks",
                "open": "(`)",
                "close": "(`)",
                "style": "single_quote",
                "scopes": ["string.interpolated.ruby", "string.interpolated.backtick.shell"],
                "language_filter": "whitelist",
                "language_list": ["Ruby", "Shell-Unix-Generic"],
                "sub_bracket_search": True
            })
```

**Comment by facelessuser** [comment] 2017-01-04 18:39
I guess I do match them as I go sort of.  I might take some shortcuts in certain areas. But yeah, I don't currently do anything with them because I don't care about them.  If brackets aren't the closest to the cursor, they get tossed.  And I stop matching as soon as I have the bracket of interest matched.  It may not be as helpful as you would think...maybe the initial brackets, but anything after the target match would be missing I imagine...I'd have to look at the algorithm again.

**Comment by facelessuser** [comment] 2017-01-04 18:40
> Shall I do a pull request and place this into the bh_core.sublime_settings file?

Yes.  I think someone has requested it before, so imagine there will be some happy people.

**Comment by facelessuser** [comment] 2017-04-23 00:16
The purpose of this plugin wasn't necessarily to provide a match library for other plugins in ST.  Though I am not against it being used as such, it is more work to make it so than I have time to do.  I am going to go ahead and close this.  If I have time in the future and find the motivation to do so.

**Closed by facelessuser** 2017-04-23 00:16 UTC
Labels: Discussion
